(ns hinagata.methods.maturity
  "hinagata 雛形 — maturity dashboard generator (ADR-2606111954).
  1:1 Clojure port of `methods/maturity.py`.

  Rolls up every measured dimension of the legal-template commons — size, statute grounding,
  legal-system / language / per-jurisdiction breadth, integrity, and the eight globally-grounded
  core clauses — into a single MATURITY.md scorecard with an honest readiness assessment. This is
  the actor's maturity SSoT: generated, never hand-edited, so it cannot drift from the graph.

  CONSTITUTIONAL: G1 — a COMMONS, never the practice of law; G3/G5 — the integrity gate reports
  DISCLOSED structural facts (validate.cljc), never a verdict on the law.

  Reuses hinagata.methods.{analyze,validate}; Counter over template langs. Portable .cljc."
  (:require [clojure.string :as str]
            [clojure.set]
            [hinagata.methods.analyze :as analyze]
            [hinagata.methods.validate :as validate]))

;; the eight cross-cutting clauses the commons aims to ground worldwide
(def core-clauses
  ["cl.signature-esign" "cl.data-subject-rights" "cl.warranty-conformity"
   "cl.employment-termination" "cl.lease-term-generic" "cl.ip-assignment"
   "cl.cooling-off" "cl.dispute-arbitration"])

(defn- by-kind
  "[n for n in nodes.values() if n[:lt/kind] == kind] — in EDN read order (analyze/node-vals)."
  [nodes kind]
  (filter #(= kind (get % ":lt/kind")) (analyze/node-vals nodes)))

(defn- counter-keys
  "Distinct keys of Counter(seq) — used only for counts (set semantics), nil allowed."
  [coll]
  (reduce (fn [m v] (update m v (fnil inc 0))) {} coll))

(defn maturity
  "Render the MATURITY.md scorecard (1:1 with maturity.maturity)."
  [nodes edges]
  (let [tmpls (by-kind nodes ":template")
        clauses (by-kind nodes ":clause")
        statutes (by-kind nodes ":statute")
        jurisdictions (by-kind nodes ":jurisdiction")
        concepts (by-kind nodes ":concept")
        [errors warnings] (validate/validate nodes edges)
        langs (counter-keys (map #(get % ":template/lang") tmpls))
        systems (set (map #(get % ":jurisdiction/system") jurisdictions))
        cited (set (for [e edges :when (contains? analyze/cite-kinds (get e ":en/kind"))] (get e ":en/to")))
        bound-clauses (set (for [e edges
                                 :when (and (contains? analyze/cite-kinds (get e ":en/kind"))
                                            (= ":clause" (get-in nodes [(get e ":en/from") ":lt/kind"])))]
                             (get e ":en/from")))
        translated (set (for [e edges :when (= ":translates" (get e ":en/kind"))] (get e ":en/from")))
        st-jx (into {} (map (fn [s] [(get s ":lt/id") (get s ":statute/jurisdiction")]) statutes))
        core-reach (into {}
                         (map (fn [cl]
                                (let [jx (set (for [e edges
                                                    :when (and (contains? analyze/cite-kinds (get e ":en/kind"))
                                                               (= cl (get e ":en/from")))]
                                                (get st-jx (get e ":en/to"))))]
                                  [cl (count (filter some? jx))]))
                              core-clauses))
        L (transient [])]
    (conj! L "# hinagata 雛形 — maturity scorecard\n")
    (conj! L (str "> GENERATED by `methods/maturity.py` from the kotoba-EDN graph — do not hand-edit. "
                  "ADR-2606111954.\n"))
    (conj! L "## Size\n")
    (conj! L "| dimension | count |")
    (conj! L "|---|---:|")
    (conj! L (str "| templates | " (count tmpls) " |"))
    (conj! L (str "| clauses | " (count clauses) " |"))
    (conj! L (str "| statutes | " (count statutes) " |"))
    (conj! L (str "| jurisdictions | " (count jurisdictions) " |"))
    (conj! L (str "| concepts | " (count concepts) " |"))
    (conj! L (str "| 縁 (edges) | " (count edges) " |"))
    (conj! L (str "| languages | " (count (filter some? (keys langs))) " |"))

    (conj! L "\n## Quality gates\n")
    (conj! L "| gate | status |")
    (conj! L "|---|:--|")
    (conj! L (str "| integrity (validate.py) | "
                  (cond
                    (and (empty? errors) (empty? warnings)) "✅ 0 errors / 0 warnings"
                    (seq errors) (str "❌ " (count errors) " errors")
                    :else (str "⚠ " (count warnings) " warnings"))
                  " |"))
    (conj! L (str "| clause statute-binding | " (count bound-clauses) "/" (count clauses) " bound |"))
    (conj! L (str "| statute grounding | "
                  (count (filter #(contains? cited (get % ":lt/id")) statutes)) "/" (count statutes)
                  " cited |"))
    (conj! L (str "| legal systems | " (count (filter some? systems)) "/6 represented |"))
    (conj! L (str "| translation linkage | " (count translated) "/" (count tmpls) " templates linked |"))

    (conj! L "\n## Core-clause worldwide grounding (the 8 most cross-cutting concerns)\n")
    (conj! L "| clause | jurisdictions grounded |")
    (conj! L "|---|---:|")
    (doseq [cl core-clauses]
      (let [lbl (get-in nodes [cl ":lt/label"] cl)]
        (conj! L (str "| " lbl " | " (get core-reach cl 0) " |"))))

    ;; honest readiness line
    (let [ok (and (empty? errors)
                  (= 6 (count (filter some? systems)))
                  (>= (count langs) 6)
                  (>= (count bound-clauses) (- (count clauses) 3)))]
      (conj! L "\n## Readiness\n")
      (conj! L (if ok
                 (str "**R1 — mature**: clean integrity, all 6 legal systems, multilingual, core clauses "
                      "globally grounded. Live legal-corpus binding + IPFS pin/IPNS remain G7-gated.")
                 "**R0/R1 — in progress**: see gaps above.")))
    (conj! L "\n---\n_hinagata 雛形 · ADR-2606111954 · generated maturity scorecard._\n")
    (str/join "\n" (persistent! L))))

#?(:clj
   (defn -main
     "CLI entry: generate MATURITY.md from a seed EDN graph. File I/O at the edge."
     [& argv]
     (let [argv (vec argv)
           here (-> *file* clojure.java.io/file .getParentFile .getParentFile)
           seed (if (and (seq argv) (not (str/starts-with? (first argv) "--")))
                  (clojure.java.io/file (first argv))
                  (clojure.java.io/file here "data" "seed-legal-template-graph.kotoba.edn"))
           {:keys [nodes edges]} (analyze/load-file* seed)]
       (spit (clojure.java.io/file here "MATURITY.md") (maturity nodes edges))
       (println (str "hinagata maturity → " (clojure.java.io/file here "MATURITY.md")))
       0)))
