#!/usr/bin/env python3
"""ooyake 公 — gov-atlas integrity + coverage validator (ADR-2606021600).

Validates a gov-units.json index (the artifact served at
etzhayyim.com/.well-known/gov-units.json and generated by
50-infra/etzhayyim-did-web/scripts/gen-gov-atlas-index.mjs). Read-only, offline by
default; pass --url to validate the live endpoint. Exits non-zero on any integrity
failure (suitable for CI / pre-deploy gate).

Checks:
  1. ids unique
  2. every non-null :parent resolves to an existing unit id (no dangling refs)
  3. level ∈ the schema enum; sourcing ∈ {authoritative, representative}
  4. every municipality/ward has a country/prefecture ancestor that exists
  5. authoritative scope == bootstrap attestation (only gov.jpn.pref.* / gov.jpn.city.*)
  6. summary fields (count, byLevel, bySourcing) match the actual units

Prints a coverage report (by level, by sourcing, jurisdictions).
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import urllib.request

LEVELS = {"supranational", "country", "region", "subdivision", "prefecture",
          "municipality", "ward", "ministry", "agency", "bureau", "division",
          "section", "madoguchi", "legislature", "court", "cabinet"}
SOURCING = {"authoritative", "representative"}

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.normpath(os.path.join(_HERE, "..", "..", ".."))
DEFAULT_FILE = os.path.join(_REPO, "50-infra/etzhayyim-did-web/out/gov-units.json")


def load(src):
    if src.startswith("http"):
        # validating our OWN public endpoint; set a UA so CF bot-management doesn't
        # 403 the default python-urllib agent (not auth circumvention — G4 intact).
        req = urllib.request.Request(src, headers={"user-agent": "ooyake-atlas-validator/1.0 (+https://etzhayyim.com)"})
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.loads(r.read().decode("utf-8"))
    return json.load(open(src, encoding="utf-8"))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", help="validate the live endpoint instead of the local file")
    ap.add_argument("--file", default=DEFAULT_FILE)
    args = ap.parse_args()
    src = args.url or args.file
    # The generated public index (gov-units.json) is a build artifact, not committed
    # (gitignored under 50-infra/.../out/). When it is absent and we are not validating
    # a live --url, skip gracefully: the EDN registry is the SSoT and is covered by
    # scripts/check_seed_integrity.py; this validator is a PRE-DEPLOY gate for the
    # generated/published artifact only.
    if not args.url and not os.path.exists(src):
        print(f"validate_atlas: skip — generated index absent ({src}); "
              f"EDN registry is validated by check_seed_integrity.py")
        return 0
    d = load(src)
    units = d.get("units", [])
    ids = [u["id"] for u in units]
    idset = set(ids)
    fail = []

    # 1 unique ids
    if len(ids) != len(idset):
        dups = {x for x in ids if ids.count(x) > 1}
        fail.append(f"duplicate ids: {sorted(dups)[:10]}")

    # 2 parent refs resolve
    dangling = [u["id"] for u in units if u.get("parent") and u["parent"] not in idset]
    if dangling:
        fail.append(f"{len(dangling)} dangling parent refs (e.g. {dangling[:5]})")

    # 3 level / sourcing enums
    bad_lvl = sorted({u.get("level") for u in units if u.get("level") not in LEVELS})
    bad_src = sorted({u.get("sourcing") for u in units if u.get("sourcing") not in SOURCING})
    if bad_lvl:
        fail.append(f"invalid levels: {bad_lvl}")
    if bad_src:
        fail.append(f"invalid sourcing: {bad_src}")

    # 4 municipality/ward has a resolvable ancestor chain to a country
    def ancestor_country(u):
        seen = set()
        cur = u
        while cur and cur.get("parent"):
            if cur["id"] in seen:
                return None  # cycle
            seen.add(cur["id"])
            cur = next((x for x in units if x["id"] == cur["parent"]), None)
            if cur and cur.get("level") in ("country", "supranational"):
                return cur["id"]
        return cur["id"] if cur and cur.get("level") in ("country", "supranational") else None
    no_country = [u["id"] for u in units if u.get("level") in ("municipality", "ward")
                  and ancestor_country(u) is None]
    if no_country:
        fail.append(f"{len(no_country)} municipalities/wards without a country ancestor (e.g. {no_country[:5]})")

    # 5 authoritative scope = bootstrap attestation (JP pref/city only)
    auth_out_of_scope = [u["id"] for u in units if u.get("sourcing") == "authoritative"
                         and not (u["id"].startswith("gov.jpn.pref.") or u["id"].startswith("gov.jpn.city."))]
    if auth_out_of_scope:
        fail.append(f"{len(auth_out_of_scope)} authoritative units outside the bootstrap-attested JP backbone (e.g. {auth_out_of_scope[:5]})")

    # 6 summary fields match
    by_level = {}
    by_src = {}
    for u in units:
        by_level[u.get("level")] = by_level.get(u.get("level"), 0) + 1
        by_src[u.get("sourcing")] = by_src.get(u.get("sourcing"), 0) + 1
    if d.get("count") != len(units):
        fail.append(f"count field {d.get('count')} != actual {len(units)}")
    if d.get("byLevel") and d["byLevel"] != by_level:
        fail.append("byLevel summary mismatch")
    if d.get("bySourcing") and d["bySourcing"] != by_src:
        fail.append("bySourcing summary mismatch")

    jurisdictions = len({u["jurisdiction"].split("-")[0] for u in units if u.get("jurisdiction")})
    print(f"gov-atlas validate — source: {src}")
    print(f"  units={len(units)} jurisdictions={jurisdictions}")
    print(f"  byLevel={json.dumps(by_level, ensure_ascii=False)}")
    print(f"  bySourcing={json.dumps(by_src, ensure_ascii=False)}")
    print(f"  parent-refs: {len(units) - len(dangling)}/{len(units)} resolve")
    print(f"  authoritative scope: {by_src.get('authoritative', 0)} units, all in JP pref/city backbone: {not auth_out_of_scope}")
    if fail:
        print("INTEGRITY FAILURES:")
        for f in fail:
            print(f"  ✗ {f}")
        return 1
    print("  ✓ all integrity checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
