"""tanemaki 種蒔き — kotoba pywasm component entry (ADR-2606122001).

Implements the five `etzhayyim:tanemaki/tanemaki-actor` world exports (wit/world.wit). The
bounded SYNTHETIC seed is embedded read-only (`wasm/_embedded_seed.py`, generated by build.sh)
so the component needs no FS/network at runtime — G1 (steward-not-sovereign) and no-server-key
hold in WASM (the `propose` export builds an UNSENT advisory record and refuses ineligible
orgs; nothing in the component can move funds or cast a vote).

Runnable as plain Python (dev mode): falls back to the on-disk seed when the embedded module is
absent, so `python3 wasm/app.py {analyze|datoms|coverage|scorecard|propose}` verifies the exports.
"""
from __future__ import annotations
import sys, json, pathlib

_HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent / "methods"))

import analyze as _analyze            # noqa: E402
import datom_emit as _datom_emit      # noqa: E402
import coverage_report as _coverage   # noqa: E402
import propose as _propose            # noqa: E402


def _seed_text() -> str:
    try:
        from _embedded_seed import SEED_EDN  # generated by build.sh; absent in dev
        return SEED_EDN
    except ImportError:
        return (_HERE.parent / "data" / "seed-stewardship-graph.kotoba.edn").read_text(encoding="utf-8")


def _load():
    forms = _analyze.read_edn(_seed_text())
    nodes, edges = {}, []
    for f in forms:
        if not isinstance(f, dict):
            continue
        if ":fs/id" in f:
            nodes[f[":fs/id"]] = f
        elif ":en/from" in f and ":en/to" in f:
            edges.append(f)
    return nodes, edges


def analyze() -> str:
    nodes, edges = _load()
    res = _analyze.analyze(nodes, edges)
    orgs = {oid: {"route": r["route"], "dd_fit": r["dd_fit"],
                  "evidence_coverage": r["evidence_coverage"],
                  "conflicts": r["conflicts"], "undetermined": r["undetermined"],
                  "synthetic": r["synthetic"]}
            for oid, r in res["orgs"].items()}
    return json.dumps({"orgs": orgs, "criteria": res["criteria"],
                       "decidedBy": "1-sbt-1-vote"}, ensure_ascii=False)


def datoms(tx: int = 1) -> str:
    nodes, edges = _load()
    return _datom_emit.emit(nodes, edges, _analyze.analyze(nodes, edges), int(tx))


def coverage() -> str:
    nodes, edges = _load()
    return _coverage.report(nodes, edges)


def scorecard(org_id: str) -> str:
    nodes, edges = _load()
    return _propose.render_scorecard(org_id, nodes, edges)


def propose(org_id: str, amount_usdc_micros: int, instrument: str, justification: str) -> str:
    nodes, edges = _load()
    try:
        rec = _propose.build_proposal(org_id, nodes, edges,
                                      amount_usdc_micros=int(amount_usdc_micros),
                                      instrument=instrument or ":grant",
                                      justification=justification or "")
        return json.dumps(rec, ensure_ascii=False)
    except AssertionError as ex:
        return json.dumps({"$type": "com.etzhayyim.tanemaki.ddScorecard",
                           "orgId": org_id, "refused": True, "reason": str(ex)},
                          ensure_ascii=False)


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "analyze"
    if cmd == "analyze":
        print(analyze())
    elif cmd == "datoms":
        print(datoms(int(sys.argv[2]) if len(sys.argv) > 2 else 1))
    elif cmd == "coverage":
        print(coverage())
    elif cmd == "scorecard":
        print(scorecard(sys.argv[2] if len(sys.argv) > 2 else "org.osslib"))
    elif cmd == "propose":
        print(propose(sys.argv[2] if len(sys.argv) > 2 else "org.foodbank",
                      int(sys.argv[3]) if len(sys.argv) > 3 else 0,
                      sys.argv[4] if len(sys.argv) > 4 else ":grant",
                      sys.argv[5] if len(sys.argv) > 5 else ""))
    else:
        print(f"unknown export: {cmd}", file=sys.stderr); sys.exit(1)
