#!/usr/bin/env bash
# tanemaki 種蒔き — build the kotoba pywasm component + content-address it (ADR-2606122001).
# Operator/mesh-side. Requires componentize-py (NOT a runtime dep):
#   pipx install componentize-py
#
# Produces dist/tanemaki.wasm (implementing wit/world.wit), its CIDv1, and the DID-doc service
# descriptor. The component embeds the bounded SYNTHETIC seed only — G1 (steward-not-sovereign)
# and no-server-key hold in WASM (the `propose` export builds an UNSENT advisory record,
# refusing screen-conflicting / under-evidenced orgs; nothing can move funds or vote).
set -euo pipefail
cd "$(dirname "$0")"
DIST="dist"; mkdir -p "$DIST"

python3 - <<'PY'
import pathlib, json
seed = pathlib.Path("../data/seed-stewardship-graph.kotoba.edn").read_text(encoding="utf-8")
pathlib.Path("_embedded_seed.py").write_text(
    "# GENERATED by wasm/build.sh — bounded SYNTHETIC stewardship seed for the WASM component.\n"
    "# tanemaki is a STEWARD, never a sovereign; every grant is decided by 1 SBT = 1 vote (G1).\n"
    "SEED_EDN = " + json.dumps(seed) + "\n", encoding="utf-8")
print("embedded seed →", len(seed), "bytes")
PY

componentize-py -d wit -w tanemaki-actor componentize app \
  --module-path . --module-path ../methods \
  -o "$DIST/tanemaki.wasm"

CID=$(ipfs add -Q --cid-version=1 --raw-leaves "$DIST/tanemaki.wasm")
echo "$CID" > "$DIST/tanemaki.cid"
echo "component CID: $CID"

python3 - "$CID" <<'PY'
import sys, json, pathlib
cid = sys.argv[1]
svc = {
  "id": "did:web:etzhayyim.com:actor:tanemaki#wasm",
  "type": "EtzhayyimWasmComponent",
  "serviceEndpoint": f"ipfs://{cid}",
  "world": "etzhayyim:tanemaki/tanemaki-actor@0.1.0",
  "exports": ["analyze", "datoms", "coverage", "scorecard", "propose"],
  "tier": "T1-raw-browser-local",
  "scope": "SYNTHETIC stewardship seed only — steward-not-sovereign, advisory DD; every grant decided by 1 SBT = 1 vote (G1); give-only instruments (G2); no-server-key"
}
pathlib.Path("did-service.json").write_text(json.dumps(svc, indent=2) + "\n", encoding="utf-8")
print("DID service descriptor → wasm/did-service.json (ipfs://%s)" % cid)
PY

echo "OK — advertise wasm/did-service.json in the actor did.json (ipfs://$CID)."
