(ns tatara.methods.maturity
  "tatara 鑪 — maturity scorecard generator (ADR-2606171800).

  Rolls up every measured dimension of the actor — seed coverage (plants / sectors / countries /
  employment / capacity), geographic concentration, chokepoint export-dependence, kabuto linkage,
  and an artifact-presence R0→R1 checklist — into a single MATURITY.md. Generated from the live
  graph + the filesystem, never hand-edited, so it cannot drift from reality.

  cljc-native; reuses analyze + crosscheck. File I/O only behind #?(:clj …)."
  (:require [clojure.string :as str]
            [clojure.java.io :as io]
            [tatara.methods.analyze :as az]
            [tatara.methods.crosscheck :as cc]))

;; ── the R0→R1 checklist: [label relative-paths-any-of] — ✅ iff a path exists ──
(def checklist
  [["ADR-2606171800 (master)"                          ["../../90-docs/adr/2606171800-tatara-global-manufacturing-plant-kg.md"]]
   ["manifest + README + CLAUDE.md"                     ["manifest.edn" "README.md" "CLAUDE.md"]]
   ["ontology (manufacturing-plant-ontology)"           ["../../00-contracts/schemas/manufacturing-plant-ontology.kotoba.edn"]]
   ["seed graph (:representative)"                       ["data/seed-plant-graph.kotoba.edn"]]
   ["analyze engine (HHI / chokepoint / capacity)"      ["methods/analyze.cljc"]]
   ["kotoba EAVT commit-DAG persistence"                ["methods/kotoba.cljc"]]
   ["autonomous autorun heartbeat"                      ["methods/autorun.cljc"]]
   ["kabuto-linkage crosscheck + worklist"              ["methods/crosscheck.cljc"]]
   ["kotoba-native lexicons (register/record)"          ["../../00-contracts/lexicons/com/etzhayyim/tatara/registerPlant.json"]]
   ["viz: plant globe (C)"                              ["viz/plant-globe.htm"]]
   ["viz: integrated world-supply globe (A)"            ["viz/world-supply-globe.htm"]]
   ["viz: watari craft globe (B)"                       ["../watari/viz/craft-globe.htm"]]
   ["DID registered (INFRA_ACTORS)"                     ["../../50-infra/etzhayyim-did-web/src/registry/infra-actors.ts"]]
   ["static did.json + profile (public/actor)"          ["../../50-infra/etzhayyim-did-web/public/actor/tatara/did.json" "../../50-infra/etzhayyim-did-web/public/actor/tatara/profile.json"]]
   ["ADR registered in docs.json registry"              ["../../90-docs/adr/2606171800-tatara-global-manufacturing-plant-kg.md"]]
   ["test suites (analyze/kotoba/autorun/lexicons/crosscheck/maturity/compose/viz/seed-integrity)" ["methods/test_analyze.cljc" "methods/test_compose.cljc"]]])

(def deferred
  [["Murakumo fleet cell placement" "R1 — the Python cell-runner (cells.edn) imports a Python module; tatara is cljc-native, so a cljc-capable runner path or a Python shim is the prerequisite."]
   ["close the kabuto crosscheck worklist" "未 — the unresolved operators need kabuto org.corp.* entries (cross-actor; kabuto seed edit)."]
   ["live ingest (disclosures / GLEIF / OSM)" "G7 — Council + operator gated; R0 ships a bounded seed only."]])

#?(:clj
   (defn- exists-rel? [base paths]
     (every? (fn [p] (.exists (io/file base p))) paths)))

(defn scorecard
  "Pure: derive the metric map from an analyze result + (optional) crosscheck result."
  [a cc-res]
  {:plants (:n-plants a)
   :hubs (:n-hubs a)
   :flows (:n-flows a)
   :chokepoints (:n-chokepoints a)
   :sectors (count (:sector-stats a))
   :countries (count (:country-roll a))
   :employment (:global-headcount a)
   :sector-stats (:sector-stats a)
   :chokes (mapv (fn [cp] [(name cp) (count (get-in a [:choke-plants cp]))]) (az/chokes-by-load a))
   :linkage (when cc-res {:resolved (:resolved cc-res) :total (:total cc-res)
                          :coverage (:coverage cc-res) :worklist (count (:worklist cc-res))})})

(defn render
  "Render MATURITY.md. `done` = vector of [label ✅?] in checklist order."
  [sc done]
  (let [P (fn [L s] (conj L s))
        pct (fn [x] (int (* 100 x)))
        L (-> []
              (P "# tatara 鑪 — maturity scorecard")
              (P "")
              (P (str "> GENERATED by `methods/maturity.cljc` from the live graph + filesystem — "
                      "do not hand-edit. ADR-2606171800. honest framing: unfinished items say so."))
              (P "")
              (P "## Coverage")
              (P "")
              (P "| dimension | count |")
              (P "|---|---:|")
              (P (str "| plants | " (:plants sc) " |"))
              (P (str "| logistics hubs | " (:hubs sc) " |"))
              (P (str "| export flows | " (:flows sc) " |"))
              (P (str "| chokepoints (geographic nodes) | " (:chokepoints sc) " |"))
              (P (str "| sectors | " (:sectors sc) " |"))
              (P (str "| countries | " (:countries sc) " |"))
              (P (str "| aggregate employment (disclosed, never per-worker) | " (:employment sc) " |"))
              (P "")
              (P "## Geographic concentration (per-sector country HHI)")
              (P "")
              (P "| sector | plants | HHI | top country | single-source? |")
              (P "|---|---:|---:|---|:--:|"))
        L (reduce (fn [L [s st]]
                    (P L (str "| " (name s) " | " (:plants st) " | " (:hhi st) " | "
                              (:top-country st) " | " (if (:single-source st) "⚠ yes" "no") " |")))
                  L (sort-by (fn [[s st]] [(- (:plants st)) (name s)]) (:sector-stats sc)))
        L (-> L
              (P "")
              (P "## Chokepoint export-dependence (composes with watari + watatsuna)")
              (P "")
              (P "| chokepoint | plants |")
              (P "|---|---:|"))
        L (reduce (fn [L [cp n]] (P L (str "| `" cp "` | " n " |"))) L (:chokes sc))
        L (-> L
              (P "")
              (P "## Cross-actor linkage (kabuto)"))
        L (if-let [lk (:linkage sc)]
            (-> L (P "")
                (P (str "- :plant/operator ⇄ kabuto :company/id: **" (:resolved lk) "/" (:total lk)
                        " = " (pct (:coverage lk)) "%** resolved · **" (:worklist lk)
                        "** on the ingest worklist")))
            (-> L (P "") (P "- kabuto seed not found — linkage not measured this run")))
        L (-> L
              (P "")
              (P "## R0→R1 checklist")
              (P "")
              (P "| item | status |")
              (P "|---|:--:|"))
        L (reduce (fn [L [label ok]] (P L (str "| " label " | " (if ok "✅" "未") " |"))) L done)
        L (-> L (P "") (P "## Deferred / gated") (P "") (P "| item | note |") (P "|---|---|"))
        L (reduce (fn [L [label note]] (P L (str "| " label " | " note " |"))) L deferred)
        n-done (count (filter second done))
        L (-> L
              (P "")
              (P "---")
              (P (str "*R0→R1 checklist: **" n-done "/" (count done) "** landed. "
                      "R0 design-only; live ingest G7 Council+operator-gated.*")))]
    (str (str/join "\n" L) "\n")))

#?(:clj
   (defn -main [& _]
     (let [cand (-> *file* io/file .getAbsoluteFile .getParentFile .getParentFile)   ; tatara/
           here (if (.exists (io/file cand "data" "seed-plant-graph.kotoba.edn"))
                  cand (io/file "20-actors" "tatara"))
           plant-seed (io/file here "data" "seed-plant-graph.kotoba.edn")
           kab-seed (io/file (.getParentFile (.getAbsoluteFile here)) "kabuto" "data" "seed-public-companies.kotoba.edn")
           rows (az/load-edn plant-seed)
           a (az/analyze (az/classify rows))
           cc-res (when (.exists kab-seed)
                    (cc/crosscheck (filter :plant/id rows) (filter :company/id (az/load-edn kab-seed))))
           done (mapv (fn [[label paths]] [label (exists-rel? here paths)]) checklist)
           sc (scorecard a cc-res)
           md (render sc done)]
       (spit (io/file here "MATURITY.md") md)
       (println (str "tatara maturity: " (count (filter second done)) "/" (count done)
                     " checklist items landed; " (:plants sc) " plants / " (:sectors sc)
                     " sectors / " (:countries sc) " countries"
                     (when cc-res (str "; kabuto linkage " (int (* 100 (:coverage cc-res))) "%"))))
       0)))
