#!/usr/bin/env bb
;; rasen 螺旋 — PUBLISH the ingested public-genetics graph to public IPFS.
(ns rasen.methods.publish
  "publish.cljc — rasen 螺旋 IPFS-pin + IPNS-publish + git-tracked snapshot (ADR-2606101000).

  Clojure/bb port of `methods/publish.py`. Keeps publish.py (additive port).

  Takes the locally ingested artifacts (out/ingested-genome-*.kotoba.edn) and:
    1. Computes the local CID via rasen.methods.cid/cidv1-raw (pure, no daemon).
    2. Pins them via `ipfs add` (shell) and asserts daemon CID == local CID (content-address
       trust anchor; the ipfs CLI is injected via `ipfs-fn` for tests).
    3. Publishes the graph CID under the node's IPNS self key → stable /ipns/<name>.
    4. Snapshots artifacts into 80-data/genome/ with PUBLISH.md + publish-manifest.json.

  PUBLIC reference data only (G1) — no individual genotypes; publishing is safe by construction.

  IO legs (ipfs CLI, file I/O) are inside #?(:clj …) guards — the pure helpers (manifest
  assembly, PUBLISH.md generation) are platform-agnostic. The `ipfs-fn` parameter is
  injectable (tests pass a dry-run stub; default uses babashka.process/shell).

  No network/subprocess I/O at load/require time."
  (:require [clojure.string :as str]
            [rasen.methods.cid :as cid-lib]
            #?(:clj [clojure.java.io :as io])))

(def gateways
  ["https://ipfs.io/ipfs/"
   "https://dweb.link/ipfs/"
   "https://cloudflare-ipfs.com/ipfs/"])

;; ── Pure helpers ─────────────────────────────────────────────────────────────

(defn artifact-entry
  "Build one artifact map entry for the manifest. All pure, no IO."
  [label filename file-bytes local-cid daemon-cid]
  {:label label
   :file  filename
   :bytes file-bytes
   :cid   local-cid
   :daemon_cid daemon-cid
   :cid_matches (= daemon-cid local-cid)})

(defn build-manifest
  "Assemble the publish-manifest map (pure). published-at is an ISO-8601 string."
  [published-at artifacts ipns-result]
  {"actor"        "rasen"
   "adr"          "2606101000"
   "published_at" published-at
   "scope"        "PUBLIC reference genetics only — no individual genotypes (G1)"
   "artifacts"    artifacts
   "ipns"         ipns-result
   "gateways"     gateways})

(defn publish-md
  "Generate the PUBLISH.md content from a manifest map (pure)."
  [m]
  (let [artifacts (get m "artifacts" {})
        g         (get artifacts "graph" {})
        d         (get artifacts "datoms" {})
        ipns      (get m "ipns" {})
        lines
        ["# rasen 螺旋 — published public-genetics graph (80-data/genome)"
         ""
         (str "> " (get m "scope") "  ·  ADR-" (get m "adr") "  ·  published " (get m "published_at"))
         ""
         "PUBLIC reference genetics (genes / variants / phenotypes / population-AGGREGATE allele"
         "frequencies / GO + Reactome pathways), content-addressed to kotoba IPFS (CIDv1, raw,"
         "sha2-256). The CID is byte-identical to `ipfs add --cid-version=1 --raw-leaves` and"
         "verifiable with `20-actors/rasen/methods/cid.py` — no daemon required."
         ""
         "## Artifacts"
         ""
         "| artifact | file | bytes | CID |"
         "|---|---|---:|---|"
         (str "| graph (EDN) | `" (or (get g "file") (get g :file) "—") "` | " (or (get g "bytes") (get g :bytes) "—") " | `" (or (get g "cid") (get g :cid) "—") "` |")
         (str "| datoms (EAVT) | `" (or (get d "file") (get d :file) "—") "` | " (or (get d "bytes") (get d :bytes) "—") " | `" (or (get d "cid") (get d :cid) "—") "` |")
         ""
         "## IPNS"
         ""
         (if-let [path (get ipns "path")]
           (str "Stable name (always resolves to the latest published graph):\n\n    " path "\n")
           "_IPNS not published this run._")
         ""
         "## Fetch + verify (trustless, no daemon trust)"
         ""
         "```bash"
         "# fetch from any public gateway and re-content-address — must equal the CID above"
         (str "curl -sSL https://ipfs.io/ipfs/" (or (get g "cid") (get g :cid) "<cid>") " -o graph.edn")
         "python3 20-actors/rasen/methods/cid.py graph.edn   # prints the CID; compare"
         "```"
         ""
         (str "Gateways: " (str/join ", " (get m "gateways" [])))
         ""
         "---"
         (str "_Generated by `20-actors/rasen/methods/publish.cljc` (G7, operator/mesh-side). "
              "Large FASTA/VCF would go via DataLad→IPFS; this bounded EDN snapshot is git-tracked "
              "directly (no git-lfs, G8)._")]]
    (str (str/join "\n" lines) "\n")))

;; ── IO helpers (#?(:clj …)) ──────────────────────────────────────────────────

#?(:clj
   (do
     ;; default ipfs runner: shells out to `ipfs` binary via babashka.process
     (defn- default-ipfs-fn [& args]
       ;; Returns {:exit :out :err}; babashka.process/shell throws on non-zero exit if
       ;; not caught — we capture manually.
       (try
         (let [res (apply babashka.process/sh (concat ["ipfs"] (map str args)))]
           {:exit (:exit res) :out (str/trim (or (:out res) "")) :err (str/trim (or (:err res) ""))})
         (catch Exception e
           {:exit 1 :out "" :err (ex-message e)})))

     (defn- add-pin
       "Pin one file: run `ipfs add -Q --cid-version=1 --raw-leaves --pin=true <path>`,
       assert daemon CID == local CID. Returns artifact-entry map.
       `ipfs-fn` injectable for tests (signature: fn[& args] → {:exit :out :err})."
       [^java.io.File f label ipfs-fn]
       (let [path    (.getAbsolutePath f)
             bytes   (.length f)
             content (.readAllBytes (java.io.FileInputStream. f))
             local-cid (cid-lib/cidv1-raw content)
             res     (ipfs-fn "add" "-Q" "--cid-version=1" "--raw-leaves" "--pin=true" path)
             daemon-cid (when (zero? (:exit res)) (str/trim (:out res)))]
         (artifact-entry label (.getName f) bytes local-cid daemon-cid)))

     (defn- copy-with-final-newline
       "Copy src text to dst, ensuring a POSIX final newline."
       [^java.io.File src ^java.io.File dst]
       (let [text (slurp src :encoding "UTF-8")
             text (if (str/ends-with? text "\n") text (str text "\n"))]
         (spit dst text :encoding "UTF-8")))

     (defn- json-str
       "Minimal JSON serializer for the manifest (keys are strings, values are
       strings/numbers/booleans/nil/maps/seqs). No cheshire dependency needed here."
       [v]
       (cond
         (nil? v)     "null"
         (boolean? v) (str v)
         (number? v)  (str v)
         (string? v)  (str "\"" (-> v
                                    (str/replace "\\" "\\\\")
                                    (str/replace "\"" "\\\"")
                                    (str/replace "\n" "\\n")
                                    (str/replace "\r" "\\r")
                                    (str/replace "\t" "\\t")) "\"")
         (map? v)     (str "{" (str/join ","
                                         (map (fn [[k val]]
                                                (str (json-str (name k)) ":" (json-str val)))
                                              v)) "}")
         (sequential? v) (str "[" (str/join "," (map json-str v)) "]")
         :else (str "\"" (str v) "\"")))

     (defn- manifest-with-string-keys
       "Convert the artifact-entry maps (which use Clojure keywords) to string-keyed
       maps for JSON serialization (mirrors the Python dict structure)."
       [m]
       (-> m
           (update "artifacts"
                   (fn [arts]
                     (reduce-kv
                       (fn [acc k v]
                         (assoc acc k (reduce-kv
                                        (fn [m2 k2 v2] (assoc m2 (name k2) v2))
                                        {} v)))
                       {} (or arts {}))))))

     (defn publish!
       "Full publish pipeline. Options map:
         :graph       path to the ingested graph EDN (default out/ingested-genome-graph.kotoba.edn)
         :no-ipns?    skip IPNS publish
         :offline-ipns? pass --allow-offline to ipns publish
         :ipfs-fn     injectable ipfs runner (default: default-ipfs-fn)
         :now         ISO-8601 string for published_at (default: current UTC)

       Returns {:ok true/false :manifest <map> :error <str-if-any>}."
       ([] (publish! {}))
       ([opts]
        (let [here      (-> *file* io/file .getParentFile .getParentFile)
              graph-f   (io/file (or (:graph opts) (str (.getAbsolutePath here) "/out/ingested-genome-graph.kotoba.edn")))
              datoms-f  (io/file (.getParentFile graph-f)
                                 (str/replace (.getName graph-f) "graph." "datoms."))
              prov-f    (io/file here "out" "ingest-provenance.json")
              ipfs-fn   (or (:ipfs-fn opts) default-ipfs-fn)
              no-ipns?  (:no-ipns? opts false)
              offline?  (:offline-ipns? opts false)
              now       (or (:now opts)
                            (.toString (java.time.Instant/now)))]

          (when-not (.exists graph-f)
            (throw (ex-info (str "publish: " (.getAbsolutePath graph-f)
                                 " not found — run methods/ingest.py first") {})))

          ;; 1. pin graph + datoms, assert CID parity
          (let [artifacts
                (reduce
                  (fn [acc [label f]]
                    (if-not (.exists f)
                      acc
                      (let [entry (add-pin f label ipfs-fn)]
                        (when-not (:cid_matches entry)
                          (throw (ex-info (str "publish: CID mismatch on " label
                                               " (daemon=" (:daemon_cid entry) ")")
                                          {:entry entry})))
                        (assoc acc label entry))))
                  {}
                  [["graph" graph-f] ["datoms" datoms-f]])

                graph-cid (get-in artifacts ["graph" :cid])

                ;; 2. IPNS publish
                ipns-result
                (when-not no-ipns?
                  (let [args (cond-> ["name" "publish" "--key=self"]
                               offline? (conj "--allow-offline"))
                        res  (apply ipfs-fn (conj (vec args) (str "/ipfs/" graph-cid)))]
                    (if (zero? (:exit res))
                      (let [line (:out res)
                            name (when (str/includes? line "Published to")
                                   (-> (str/split line #"Published to" 2)
                                       second
                                       (str/split #":" 2)
                                       first
                                       str/trim))]
                        {"name" name "path" (when name (str "/ipns/" name)) "points_to" graph-cid})
                      {"error" (subs (:err res) 0 (min 200 (count (:err res))))})))

                manifest (build-manifest now artifacts ipns-result)

                ;; 3. snapshot into 80-data/genome/
                data-dir (io/file (.getParentFile (.getParentFile here)) "80-data" "genome")]

            (.mkdirs data-dir)
            (doseq [[_ f] [["graph" graph-f] ["datoms" datoms-f]]
                    :when (.exists f)]
              (copy-with-final-newline
                f
                (io/file data-dir (str/replace (.getName f) "ingested-" ""))))
            (when (.exists prov-f)
              (copy-with-final-newline prov-f (io/file data-dir "ingest-provenance.json")))

            ;; write manifest JSON
            (let [m-str (json-str (manifest-with-string-keys manifest))]
              (spit (io/file data-dir "publish-manifest.json")
                    (str m-str "\n") :encoding "UTF-8"))
            ;; write PUBLISH.md
            (spit (io/file data-dir "PUBLISH.md")
                  (publish-md (manifest-with-string-keys manifest))
                  :encoding "UTF-8")

            (println (str "publish: snapshot → " (.getAbsolutePath data-dir)
                          "  (graph CID " graph-cid ")"))
            {:ok true :manifest manifest}))))))

;; ── CLI entrypoint (bb direct invocation) ────────────────────────────────────

#?(:clj
   (when (= *file* (System/getProperty "babashka.file"))
     (let [args (vec *command-line-args*)
           opts {:no-ipns?      (boolean (some #{"--no-ipns"} args))
                 :offline-ipns? (boolean (some #{"--offline-ipns"} args))
                 :graph         (when-let [i (.indexOf args "--graph")]
                                  (when (pos? i) (nth args (inc i) nil)))}]
       (try
         (publish! opts)
         (System/exit 0)
         (catch Exception e
           (binding [*out* *err*]
             (println (ex-message e)))
           (System/exit 1))))))

#?(:clj
   (defn -main
     "CLI entry: mirrors publish.main — content-address the ingested genome graph + datoms to
     kotoba CIDv1 (ipfs pin + IPNS publish). --graph PATH / --no-ipns / --offline-ipns.
     ADR-2606261200 cljc-native operator leg (was `python3 methods/publish.py`)."
     [& argv]
     (let [argv  (vec argv)
           here  (let [f  (when (and *file* (not (str/blank? *file*))) (io/file *file*))
                       pp (some-> f .getAbsoluteFile .getParentFile .getParentFile)]
                   (if (and pp (.isDirectory (io/file pp "data"))) pp (io/file "20-actors" "rasen")))
           graph (if (some #{"--graph"} argv) (nth argv (inc (.indexOf argv "--graph")))
                     (str (io/file here "out" "ingested-genome-graph.kotoba.edn")))]
       ;; mirror the Python main's pre-checks (publish! reads the graph eagerly).
       (when-not (.exists (io/file graph))
         (binding [*out* *err*]
           (println (str "publish: " graph " not found — run methods/ingest first")))
         (System/exit 1))
       (let [res (publish! {:graph         graph
                            :no-ipns?      (boolean (some #{"--no-ipns"} argv))
                            :offline-ipns? (boolean (some #{"--offline-ipns"} argv))})]
         (if (:ok res)
           (let [arts (get (:manifest res) "artifacts")]
             (println (str "[rasen/publish] genome graph content-addressed — " (count arts) " artifacts:"))
             (doseq [[label v] arts] (println (str "  pin " label ": " (get v "cid")))))
           (binding [*out* *err*]
             (println (str "publish failed: " (:error res)))
             (System/exit 1)))))))
