;; coverage.clj — 弾正 (danjo) revenue-ledger HONEST coverage report + maturity scorecard.
;; ADR-2605301600. The matsurigoto `coverage.md` discipline: report what is covered and what is
;; NOT, never inflate. `report` computes the numbers; `coverage-md` renders the scorecard;
;; `-main` regenerates data/REVENUE-COVERAGE.md.
;;
;; Honesty (danjo G5 / matsurigoto G5 coverage-honesty): traceability is reported per (tax, fy),
;; non-traceable taxes are counted as non-traceable (NOT hidden), and reconciliations split into
;; within-budget vs divergence vs outlay-without-appropriation-trace (partial-corpus, declared).
(ns root.danjo.methods.coverage
  (:require [clojure.string :as str]
            [clojure.java.io :as io]))

(load-file "discrepancy.clj")   ; loads revenue_ledger.clj too
(load-file "ingest.clj")
(load-file "org_actor.clj")     ; loads taxes.clj too
(alias 'rl 'root.danjo.methods.revenue-ledger)
(alias 'd  'root.danjo.methods.discrepancy)
(alias 'in 'root.danjo.methods.ingest)
(alias 't  'root.danjo.methods.taxes)
(alias 'o  'root.danjo.methods.org-actor)

(defn- oku [jpy] (format "%.1f兆" (/ (double jpy) 1.0e12)))  ; 兆円 for readability

(defn fiscal-years [model]
  (sort (distinct (concat (map :fiscal-year (:revenue-lines model))
                          (map :fiscal-year (:transfers model))
                          (map :fiscal-year (:appropriations model))
                          (map :fiscal-year (:outlays model))))))

(defn tax-kinds [model] (sort (distinct (map :tax-kind (:revenue-lines model)))))

(defn report
  "Honest coverage map over an ingested model."
  [model]
  (let [fys   (fiscal-years model)
        taxes (tax-kinds model)
        traces (vec (for [fy fys t taxes
                          :when (some #(and (= (:tax-kind %) t) (= (:fiscal-year %) fy))
                                      (:revenue-lines model))]
                      (let [tr (rl/trace model t fy)]
                        {:tax t :fiscal-year fy :traceable? (:traceable? tr)
                         :per-yen? (:per-yen? tr) :residual (:residual tr)
                         :reason (:reason tr)})))
        recon  (mapcat #(d/reconcile model %) fys)
        cat-n  (fn [c] (count (filter #(= c (:category %)) recon)))]
    {:fiscal-years fys
     :tax-kinds taxes
     :accounts (mapv (fn [a] {:id (:id a) :earmark? (:earmark? a)}) (:accounts model))
     :counts {:revenue-lines  (count (:revenue-lines model))
              :transfers      (count (:transfers model))
              :appropriations (count (:appropriations model))
              :outlays        (count (:outlays model))
              :datoms         (count (rl/all-datoms model))}
     :traces traces
     :traceable-tax-years    (count (filter :traceable? traces))
     :nontraceable-tax-years (count (remove :traceable? traces))
     :reconciliations
     {:total (count recon)
      :within                          (cat-n :appropriation-outlay-within)
      :outlay-exceeds-appropriation    (cat-n :outlay-exceeds-appropriation)
      :outlay-without-appropriation-trace (cat-n :outlay-without-appropriation-trace)}
     :verification-status (:verification-status model)}))

(defn- pct [n total] (if (zero? total) "—" (format "%.0f%%" (* 100.0 (/ (double n) total)))))

(defn coverage-md
  "Render the coverage report as a MATURITY-style markdown scorecard."
  [rep]
  (let [c (:counts rep) tt (count (:traces rep))]
    (str
     "# danjo 弾正 revenue-ledger — coverage scorecard\n\n"
     "_Generated by `methods/coverage.clj` (`-main`). HONEST coverage — non-traceable taxes are\n"
     "counted as non-traceable, not hidden (matsurigoto G5 / danjo G5). Verification status: **"
     (name (or (:verification-status rep) :representative)) "** — NOT an authoritative budget statement._\n\n"
     "## Scope\n\n"
     "- Fiscal years: " (str/join ", " (:fiscal-years rep)) "\n"
     "- Tax kinds: " (str/join ", " (map name (:tax-kinds rep))) "\n"
     "- Accounts: " (str/join ", " (map (fn [a] (str (:id a) (if (:earmark? a) " (earmarked)" " (fungible)"))) (:accounts rep))) "\n\n"
     "## Counts\n\n"
     "| revenue-lines | transfers | appropriations | outlays | EAVT datoms |\n"
     "|---|---|---|---|---|\n"
     "| " (:revenue-lines c) " | " (:transfers c) " | " (:appropriations c) " | " (:outlays c) " | " (:datoms c) " |\n\n"
     "## Per-yen traceability (the honest answer)\n\n"
     "Traceable tax-years: **" (:traceable-tax-years rep) "/" tt "** (" (pct (:traceable-tax-years rep) tt) ") · "
     "non-traceable (fungible 一般会計): **" (:nontraceable-tax-years rep) "/" tt "**\n\n"
     "| tax | FY | traceable? | per-yen? | residual |\n|---|---|---|---|---|\n"
     (str/join "\n" (for [t (:traces rep)]
                      (str "| " (name (:tax t)) " | " (:fiscal-year t) " | "
                           (if (:traceable? t) "✅" "❌ " ) (when-not (:traceable? t) (str (name (:reason t)))) " | "
                           (if (:per-yen? t) "✅" "—") " | "
                           (if (:traceable? t) (:residual t) "—") " |")))
     "\n\n## Appropriation↔outlay reconciliation\n\n"
     (let [r (:reconciliations rep)]
       (str "Total program-years: " (:total r) " · within-budget: **" (:within r) "** · "
            "outlay-exceeds-appropriation: " (:outlay-exceeds-appropriation r) " · "
            "outlay-without-appropriation-trace: " (:outlay-without-appropriation-trace r)
            " (partial-corpus / timing — a declared false-positive mode, not a verdict)\n"))
     "\n_danjo finds, never judges (G4). Legal characterization → human counsel via chigiri._\n")))

(defn national-md
  "Scorecard section over the WHOLE national-tax registry + the per-org keyless mirror-actors."
  [tax-reg org-reg]
  (let [s (t/summary tax-reg)
        by (:by-earmark-kind s)
        lv (:by-level s)
        lvl-line (fn [k label] (when-let [v (get lv k)]
                                 (str "- " label ": **" (:count v) "税 / " (oku (:amount-jpy v)) "円**\n")))
        row (fn [k label] (let [v (get by k {:count 0 :amount-jpy 0})]
                            (str "| " label " | " (:count v) " | " (oku (:amount-jpy v)) "円 | "
                                 (if (zero? (:total-jpy s)) "—"
                                     (format "%.0f%%" (* 100.0 (/ (double (:amount-jpy v)) (:total-jpy s))))) " |")))]
    (str
     "\n## 税の全体像 (国 + 地方)\n\n"
     "**" (:tax-count s) " 税目** / 合計 ≈ **" (oku (:total-jpy s)) "円** (representative)。\n"
     (lvl-line :national "国税") (lvl-line :local "地方税") "\n"
     "per-yen 追跡可能 (特別会計分) は **" (format "%.1f%%" (* 100 (:per-yen-traceable-share s))) "** のみ — "
     "国税の大半は fungible(一般会計)で、特定の1円の使途は会計的に追跡できない、という誠実な事実。\n\n"
     "| earmark | 税数 | 額 | 構成比 | per-yen 追跡 |\n|---|---|---|---|---|\n"
     (row :general "一般会計 (fungible)") " ❌ |\n"
     (row :statutory-purpose "目的税的 (法定充当・但し一般会計内)") " ❌ (法的充当方向のみ) |\n"
     (row :special-account "特別会計 (特定財源)") " ✅ |\n\n"
     "## 組織別 keyless mirror-actor (entity-as-actor, ADR-2606042330)\n\n"
     "実在の徴収・所管組織を `did:web:etzhayyim.com:actor:jp-<handle>` の鍵なしミラーとして射影。\n\n"
     "| 組織 | DID | role | 徴収/所管 |\n|---|---|---|---|\n"
     (str/join "\n"
       (for [org (:orgs org-reg)]
         (let [v (o/org-view (:id org) org-reg tax-reg)]
           (str "| " (:ja org) " | `" (:did org) "` | " (name (:role org)) " | "
                (if (pos? (:count (:collects v)))
                  (str "徴収 " (:count (:collects v)) "税 (" (oku (:amount-jpy (:collects v))) "円)")
                  (str "所管 " (str/join "," (map #(subs (str %) 1) (:accounts (:administers v)))))) " |"))))
     "\n")))

(defn -main [& args]
  (let [model (in/with-budget (in/ingest (or (first args) "../data/gov-revenue-corpus.jp.edn"))
                              (in/ingest-budget "../data/gov-fiscal-seed.jp.json"))
        rep   (report model)
        tax-reg (t/combine (t/load-taxes "../data/jp-national-taxes.edn")
                           (t/load-local-taxes "../data/jp-local-taxes.edn"))
        org-reg (o/load-orgs "../data/jp-fiscal-orgs.edn")
        out   (io/file "../data/REVENUE-COVERAGE.md")]
    (io/make-parents out)
    (spit out (str (coverage-md rep) (national-md tax-reg org-reg)))
    (println "wrote" (.getPath out))
    (println "  fiscal-years:" (:fiscal-years rep)
             "| national taxes:" (count (:taxes tax-reg))
             "| org-actors:" (count (:orgs org-reg))
             "| datoms:" (:datoms (:counts rep)))))
