;; registry_coverage.clj — 弾正 (danjo) fiscal-SOURCE registry HONEST coverage scorecard.
;; ADR-2605301600 + ADR-2605302245. Distinct from coverage.clj (which reports JP revenue-ledger
;; per-yen traceability): this reports the WORLDWIDE ingestion-SOURCE catalog
;; (registry/sources.seed.json) — how many jurisdictions/sourceKinds are catalogued, and how many
;; are still unverified-seed (G14: verification execution is R1+, so today's honest answer is
;; "0 verified" — this report must say that plainly, never round up).
(ns root.danjo.methods.registry-coverage
  (:require [cheshire.core :as json]
            [clojure.string :as str]
            [clojure.java.io :as io]))

(defn load-registry [path]
  (json/parse-string (slurp path) true))

(defn report
  "Honest coverage map over the fiscal-source registry (registry/sources.seed.json)."
  [registry]
  (let [srcs (:sources registry)
        by-count (fn [k] (->> srcs (map k) frequencies (into (sorted-map))))]
    {:total-sources (count srcs)
     :jurisdictions (sort (distinct (map :jurisdiction srcs)))
     :jurisdiction-count (count (distinct (map :jurisdiction srcs)))
     :by-source-kind (by-count :sourceKind)
     :by-verification-status (by-count :verificationStatus)
     :verified-count (count (remove #(= "unverified-seed" (:verificationStatus %)) srcs))
     :freshness-window-days (:freshnessWindowDays registry)}))

(defn- pct [n total] (if (zero? total) "—" (format "%.0f%%" (* 100.0 (/ (double n) total)))))

(defn coverage-md
  "Render the registry coverage report as a MATURITY-style markdown scorecard."
  [rep]
  (let [total (:total-sources rep)]
    (str
     "# danjo 弾正 fiscal-source registry — coverage scorecard\n\n"
     "_Generated by `methods/registry_coverage.clj` (`-main`). HONEST coverage (G8 non-fabrication,\n"
     "G14 verification tiers) — a catalogued source is NOT a verified source. See\n"
     "`registry/VERIFICATION.md` for the tier definitions._\n\n"
     "## Scope\n\n"
     "- Total sources catalogued: **" total "**\n"
     "- Distinct jurisdictions: **" (:jurisdiction-count rep) "** (worldwide guard ≥12; "
     "R0 seed spans " (:jurisdiction-count rep) ")\n"
     "- Freshness window: " (:freshness-window-days rep) " days\n\n"
     "## By sourceKind\n\n"
     "| sourceKind | count | share |\n|---|---|---|\n"
     (str/join "\n" (for [[k v] (:by-source-kind rep)]
                      (str "| " k " | " v " | " (pct v total) " |")))
     "\n\n## Verification status (the honest answer, G14)\n\n"
     "Verified (maintainer- or council-verified): **" (:verified-count rep) "/" total "** "
     "(" (pct (:verified-count rep) total) ")\n\n"
     "| verificationStatus | count | share |\n|---|---|---|\n"
     (str/join "\n" (for [[k v] (:by-verification-status rep)]
                      (str "| " k " | " v " | " (pct v total) " |")))
     "\n\n## Jurisdictions catalogued\n\n"
     (str/join ", " (:jurisdictions rep))
     "\n\n_This is a catalog-COVERAGE report (how much of the world is registered as an ingestion\n"
     "source), not a verification-coverage report and not a fraud/discrepancy report. danjo finds,\n"
     "never judges (G4); a catalogued source unlocks nothing until it clears G14 verification._\n")))

(defn -main [& args]
  (let [in  (or (first args) "../registry/sources.seed.json")
        out (io/file (or (second args) "../registry/COVERAGE.md"))
        rep (report (load-registry in))]
    (io/make-parents out)
    (spit out (coverage-md rep))
    (println "wrote" (.getPath out))
    (println "  sources:" (:total-sources rep)
             "| jurisdictions:" (:jurisdiction-count rep)
             "| verified:" (:verified-count rep))))
