"""
Contract test for the post_quantum-compat L4 actor.
Static API-contract verification (stdlib unittest; no WASM runtime).
Generated by 70-tools/promote_l4.py.
"""
import ast
import os
import re
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
ACTOR = os.path.dirname(HERE)
MAIN = os.path.join(ACTOR, "src", "main.py")
SCHEMA = os.path.join(ACTOR, "schema", "post_quantum.kotoba")
ENTITIES = ['KeySession', 'Node', 'Channel', 'Key', 'Protocol', 'Alarm']
PLURALS = {'KeySession': 'keysessions', 'Node': 'nodes', 'Channel': 'channels', 'Key': 'keys', 'Protocol': 'protocols', 'Alarm': 'alarms'}


class PostQuantumContract(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        with open(MAIN, encoding="utf-8") as f:
            cls.src = f.read()
        cls.tree = ast.parse(cls.src)
        with open(SCHEMA, encoding="utf-8") as f:
            cls.schema = f.read()

    def test_compiles(self):
        self.assertIsInstance(self.tree, ast.Module)

    def test_schema_has_all_entities(self):
        for ent in ENTITIES:
            self.assertRegex(self.schema, r"entity\s+" + ent + r"\s*\{",
                             f"schema missing entity {ent}")

    def test_full_crud_per_entity(self):
        for ent, plural in PLURALS.items():
            base = "/v1/" + plural
            for needle in (
                f'@app.route("{base}", methods=["POST"])',
                f'@app.route("{base}", methods=["GET"])',
                f'@app.route("{base}/<eid>", methods=["GET"])',
                f'@app.route("{base}/<eid>", methods=["DELETE"])',
            ):
                self.assertIn(needle, self.src, f"missing route: {needle}")

    def test_list_has_pagination(self):
        self.assertIn("_paginate(", self.src)
        self.assertIn("has_more", self.src)
        self.assertIn("starting_after", self.src)

    def test_list_has_filtering(self):
        self.assertIn("_apply_filters(", self.src)

    def test_validation_present(self):
        self.assertIn("_reject_unknown(", self.src)
        self.assertIn("_require(", self.src)

    def test_healthz(self):
        self.assertIn('"tier": "L4"', self.src)

    def test_no_proprietary_imports(self):
        for bad in ("requests", "openai", "stripe", "boto3"):
            self.assertNotIn("import " + bad, self.src)


if __name__ == "__main__":
    unittest.main()
