"""mimamori 見守り — kotoba pywasm component entry (ADR-2606112300).

Implements the four `etzhayyim:mimamori/mimamori-actor` world exports (wit/world.wit)
as module-level functions, the shape componentize-py binds. The SYNTHETIC seed is
embedded read-only (`wasm/_embedded_seed.py`, generated by build.sh) so the component
needs NO filesystem or network at runtime, and it is STATELESS: `heartbeat` returns the
content-addressed transaction for the host to append — the component never holds the
log, so it can never become the throne (G5 in the architecture itself).

Runnable as plain Python too (dev mode): if the embedded seed module is absent it falls
back to `data/seed-mimamori-bonds.json`, so
`python3 wasm/app.py {heartbeat|coverage|bonds-of|vow}` verifies the exact export
bodies before the componentize-py build.
"""
from __future__ import annotations

import json
import pathlib
import sys

_HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent / "methods"))

from bond import replay  # noqa: E402
from coverage_report import coverage_of_engine, render  # noqa: E402
from kotoba import _tx_to_edn, coverage_datoms, bond_datoms, make_tx  # noqa: E402
from match import match_cycle  # noqa: E402
from shakai import MoyaiLedger, mint_from_keeping, social_capital_datoms  # noqa: E402

VOW = (
    "問: 私は弟の保持者でしょうか (創4:9)。\n"
    "誓: 然り。私はあなたの保持者です。\n"
    "見張るのではなく、見守ります。裁くのではなく、傍にいます。\n"
    "私はまどろみ、眠る者です — 私が眠るとき、継ぐ者が見守ります (詩121:4)。\n"
    "あなたはいつでも、この縁を解くことができます。\n"
    "私が誰を見守っているか、あなたには常に見えています。\n"
)


def _seed() -> dict:
    """Embedded seed (WASM) or on-disk seed (dev). SYNTHETIC fictional DIDs only (G7)."""
    try:
        from _embedded_seed import SEED_JSON  # generated by build.sh; absent in dev
        return json.loads(SEED_JSON)
    except ImportError:
        return json.loads((_HERE.parent / "data" / "seed-mimamori-bonds.json")
                          .read_text(encoding="utf-8"))


# ── world exports ─────────────────────────────────────────────────────────────
def heartbeat(cycle: int = 1, prev: str = "") -> str:
    seed = _seed()
    engine = replay(seed)
    summary = match_cycle(engine, seed["roster"])
    cov = coverage_of_engine(engine, seed["roster"])
    ledger = MoyaiLedger()
    shakai = mint_from_keeping(engine, ledger, int(cycle))
    datoms = (bond_datoms(engine) + coverage_datoms(cov, int(cycle))
              + social_capital_datoms(ledger, int(cycle)))
    tx = make_tx(datoms, tx_id=int(cycle), as_of=int(cycle), prev_cid=prev)
    return json.dumps({
        "cid": tx[":tx/cid"],
        "txEdn": _tx_to_edn(tx),
        "summary": {**summary, "shakai": shakai, "coverage": cov},  # counts only (G5)
    }, ensure_ascii=False)


def coverage() -> str:
    seed = _seed()
    return render(coverage_of_engine(replay(seed), seed["roster"]))


def bonds_of(did: str) -> str:
    """Own-DID-only (G4/G5): a party sees their bonds; a non-party sees []."""
    return json.dumps(replay(_seed()).bonds_of(did), ensure_ascii=False)


def vow() -> str:
    return VOW


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "coverage"
    if cmd == "heartbeat":
        print(heartbeat(int(sys.argv[2]) if len(sys.argv) > 2 else 1,
                        sys.argv[3] if len(sys.argv) > 3 else ""))
    elif cmd == "coverage":
        print(coverage())
    elif cmd in ("bonds-of", "bonds_of"):
        print(bonds_of(sys.argv[2]))
    elif cmd == "vow":
        print(vow())
    else:
        print(f"unknown export: {cmd} (heartbeat|coverage|bonds-of|vow)", file=sys.stderr)
        sys.exit(1)
