#!/usr/bin/env bash
# mimamori 見守り — build the kotoba pywasm component + content-address it (ADR-2606112300).
# Operator/mesh-side. Requires componentize-py (NOT a runtime dep; install in the build env):
#   pipx install componentize-py   # or: pip install componentize-py
#
# Produces dist/mimamori.wasm (a WASM Component implementing wit/world.wit), its CIDv1, and
# the DID-doc service descriptor advertising it (ADR-2606013800 / 2606014500). The component
# embeds the SYNTHETIC seed only (G7) and is STATELESS — the host owns the append-only log.
set -euo pipefail
cd "$(dirname "$0")"
DIST="dist"; mkdir -p "$DIST"

# 1. embed the SYNTHETIC seed as a read-only Python module (no FS at runtime; G7)
python3 - <<'PY'
import pathlib, json
seed = pathlib.Path("../data/seed-mimamori-bonds.json").read_text(encoding="utf-8")
pathlib.Path("_embedded_seed.py").write_text(
    "# GENERATED by wasm/build.sh — SYNTHETIC seed embedded for the WASM component.\n"
    "# Fictional DIDs only (G7); the component cannot leak what it does not contain.\n"
    "SEED_JSON = " + json.dumps(seed) + "\n", encoding="utf-8")
print("embedded seed →", len(seed), "bytes")
PY

# 1b. vendor the moyai ledger (verbatim reuse, ADR-2606082100 Part A) into the module path
cp ../../../50-infra/etzhayyim-moyai-credit/methods/ledger.py _vendored_ledger_moyai.py
python3 - <<'PY'
import pathlib
p = pathlib.Path("_vendored_ledger_moyai.py")
src = p.read_text(encoding="utf-8")
pathlib.Path("ledger.py").write_text(
    "# VENDORED VERBATIM from 50-infra/etzhayyim-moyai-credit/methods/ledger.py\n"
    "# (ADR-2606082100 Part A: social capital MUST reuse the moyai ledger primitive\n"
    "# verbatim). Do not edit here — edit upstream and re-run build.sh.\n" + src,
    encoding="utf-8")
p.unlink()
print("moyai ledger vendored (verbatim + provenance header)")
PY

# 2. componentize: bind wit/world.wit, bundle app.py (+ methods + embedded seed) → component
componentize-py -d wit -w mimamori-actor componentize app \
  --module-path . --module-path ../methods \
  -o "$DIST/mimamori.wasm"

# 3. content-address (CIDv1 raw sha2-256) + pin
CID=$(ipfs add -Q --cid-version=1 --raw-leaves "$DIST/mimamori.wasm")
echo "$CID" > "$DIST/mimamori.cid"
echo "component CID: $CID"

# 4. emit the DID-doc service descriptor (apex Worker advertises this; ADR-2606013800)
python3 - "$CID" <<'PY'
import sys, json, pathlib
cid = sys.argv[1]
svc = {
  "id": "did:web:etzhayyim.com:actor:mimamori#wasm",
  "type": "EtzhayyimWasmComponent",
  "serviceEndpoint": f"ipfs://{cid}",
  "world": "etzhayyim:mimamori/mimamori-actor@0.1.0",
  "exports": ["heartbeat", "coverage", "bonds-of", "vow"],
  "tier": "T1-raw-browser-local",
  "scope": "covenant keeping membrane — SYNTHETIC seed only (G7); stateless (host owns the log, G5); live legs Council+operator gated"
}
pathlib.Path("did-service.json").write_text(json.dumps(svc, indent=2) + "\n", encoding="utf-8")
print("DID service descriptor → wasm/did-service.json (ipfs://%s)" % cid)
PY

echo "OK — advertise wasm/did-service.json in the actor did.json (ipfs://$CID)."
