(ns funadaiku.methods.test-voyage-energy
  "funadaiku 船大工 — voyage-energy tests (ADR-2606013400). 1:1 Clojure port of
  methods/test_voyage_energy.py — every assertion — over the default Nagi 凪 vessel/voyage,
  PLUS the constitutional zero-emission gate made explicit and test-enforced:

    G13 / N5 — NO fossil engine, ever. :fossil_engine is false; the energy-share map carries
      exactly {wind_assist solar hydrogen_fuelcell} and NEVER a \"fossil\" key — fossil energy
      is structurally unrepresentable. The renewable + H2 shares sum to 1.0 of total demand.
    G14 — a positive green-H₂ demand (hydrogen is the prime mover at cargo scale).

  The Python suite's test_main_writes_report_and_edn_artifacts (file I/O) is ported as a
  -main artifact test; the report()/to_edn() smoke test is strengthened to a BYTE-PARITY
  assertion against the python3-generated bytes (committed under out/, regenerated by
  voyage_energy.py). Cell/state-machine tests (cells/test_state_machines.py) are a separate
  Pregel-cell concern and out of scope here (deferred — that suite is generic over all 9
  cells and lives under cells/)."
  (:require [clojure.test :refer [deftest is run-tests]]
            [clojure.string :as str]
            [funadaiku.methods.voyage-energy :as ve]))

(defn- sim [] (ve/simulate (ve/->vessel) (ve/->voyage)))

;; Resolve the methods/ dir once at load time — *file* is bound during require here.
#?(:clj (def ^:private this-file *file*))

;; ── ported assertions (1:1 with test_voyage_energy.py) ──────────────────────

(deftest test-no-fossil-engine
  ;; G13/N5: a fossil engine must never appear; no fossil energy share may exist.
  (let [r (sim)]
    (is (false? (get r "fossil_engine")))
    (is (not (contains? (get r "shares") "fossil")))))

(deftest test-energy-shares-are-renewable-and-sum-to-one
  (let [r (sim)
        shares (get r "shares")
        total (reduce + 0.0 (vals shares))]
    (is (= #{"wind_assist" "solar" "hydrogen_fuelcell"} (set (keys shares))))
    (is (< (Math/abs (- total 1.0)) 1e-6)
        (str "renewable+H2 shares must cover 100% of demand, got " total))
    (is (every? #(>= % 0.0) (vals shares)))))

(deftest test-positive-hydrogen-demand-and-battery-window
  (let [r (sim)
        s (get r "shares")]
    (is (> (get r "h2_kg") 0)
        "a cargo-scale coastal voyage needs green-H2 (H2 is the prime mover)")
    (is (> (get r "battery_harbour_minutes") 0))
    ;; hydrogen is the dominant single source at cargo scale (the survey conclusion)
    (is (> (get s "hydrogen_fuelcell") (get s "wind_assist")))
    (is (> (get s "hydrogen_fuelcell") (get s "solar")))))

(deftest test-shaft-power-follows-admiralty-cube-law
  (let [base (ve/->vessel)
        faster (ve/->vessel :service-speed-kn (* (:service-speed-kn base) 2))
        p1 (ve/shaft-power-kw base)
        p2 (ve/shaft-power-kw faster)]
    ;; P ∝ V^3 → doubling speed ≈ 8× shaft power
    (is (< (Math/abs (- (/ p2 p1) 8.0)) 0.05)
        (str "Admiralty cube law violated: ratio=" (/ p2 p1)))))

(deftest test-higher-demand-raises-hydrogen-share
  ;; a longer / faster voyage shifts more of the budget onto hydrogen (less solar/wind cover)
  (let [short (ve/simulate (ve/->vessel) (ve/->voyage))
        longer (ve/simulate (ve/->vessel)
                            (ve/->voyage :distance-nm (* (:distance-nm (ve/->voyage)) 3)))]
    (is (> (get longer "h2_kg") (get short "h2_kg")))))

(deftest test-serializations-nonempty
  (let [v (ve/->vessel)
        voy (ve/->voyage)
        r (ve/simulate v voy)
        edn (ve/to-edn v voy r)
        rep (ve/report v voy r)]
    (is (and (string? edn) (seq (str/trim edn))))
    (is (and (string? rep) (seq (str/trim rep))))
    ;; the zero-emission datom is in the EDN serialization (mirrors the Python main artifact test)
    (is (str/includes? edn "fossil-engine false"))))

;; ── byte-parity against the python3-generated artifacts (the headline assertion) ──
#?(:clj
   (deftest test-byte-parity-with-python-artifacts
     ;; report()/to_edn() must be byte-identical to the python3 voyage_energy.py output that
     ;; produced out/voyage-energy-report.md + out/voyage-energy.kotoba.edn on the same voyage.
     (let [v (ve/->vessel)
           voy (ve/->voyage)
           r (ve/simulate v voy)
           out (clojure.java.io/file (-> this-file clojure.java.io/file .getParentFile .getParentFile) "out")
           md (clojure.java.io/file out "voyage-energy-report.md")
           edn (clojure.java.io/file out "voyage-energy.kotoba.edn")]
       (is (= (slurp md) (ve/report v voy r)))
       (is (= (slurp edn) (ve/to-edn v voy r))))))

#?(:clj
   (when (= *file* (System/getProperty "babashka.file"))
     (let [{:keys [fail error]} (run-tests 'funadaiku.methods.test-voyage-energy)]
       (System/exit (if (zero? (+ fail error)) 0 1)))))
