#!/usr/bin/env bash
# hinagata 雛形 — build the kotoba pywasm component + content-address it (ADR-2606111954).
# Operator/mesh-side. Requires componentize-py (NOT a runtime dep; install in the build env):
#   pipx install componentize-py   # or: pip install componentize-py
#
# Produces dist/hinagata.wasm (a WASM Component implementing wit/world.wit), its CIDv1, and the
# DID-doc service descriptor advertising it (ADR-2606013800 / 2606014500). The component embeds
# the bounded PUBLIC template-commons seed only — G1 (commons, not advice) holds in WASM, and
# no-server-key holds (the `envelope` export builds an UNSIGNED record only).
set -euo pipefail
cd "$(dirname "$0")"
ACTOR_DIR="$(cd .. && pwd)"
DIST="dist"; mkdir -p "$DIST"

# 1. embed the bounded PUBLIC seed as a read-only Python module (no FS at runtime)
python3 - <<'PY'
import pathlib, json
seed = pathlib.Path("../data/seed-legal-template-graph.kotoba.edn").read_text(encoding="utf-8")
pathlib.Path("_embedded_seed.py").write_text(
    "# GENERATED by wasm/build.sh — bounded PUBLIC seed embedded for the WASM component.\n"
    "# PUBLIC openly-licensed legal templates only; a commons, never advice (G1).\n"
    "SEED_EDN = " + json.dumps(seed) + "\n", encoding="utf-8")
print("embedded seed →", len(seed), "bytes")
PY

# 2. componentize: bind wit/world.wit, bundle app.py (+ methods + embedded seed) → component
#    --module-path makes the pure-stdlib methods importable inside the component.
componentize-py -d wit -w hinagata-actor componentize app \
  --module-path . --module-path ../methods \
  -o "$DIST/hinagata.wasm"

# 3. content-address (CIDv1 raw sha2-256 — parity with methods/cid.py) + pin
CID=$(ipfs add -Q --cid-version=1 --raw-leaves "$DIST/hinagata.wasm")
echo "$CID" > "$DIST/hinagata.cid"
echo "component CID: $CID"

# 4. emit the DID-doc service descriptor (apex Worker advertises this; ADR-2606013800)
python3 - "$CID" <<'PY'
import sys, json, pathlib
cid = sys.argv[1]
svc = {
  "id": "did:web:etzhayyim.com:actor:hinagata#wasm",
  "type": "EtzhayyimWasmComponent",
  "serviceEndpoint": f"ipfs://{cid}",
  "world": "etzhayyim:hinagata/hinagata-actor@0.1.0",
  "exports": ["analyze", "datoms", "coverage", "envelope"],
  "tier": "T1-raw-browser-local",
  "scope": "PUBLIC openly-licensed legal templates only — a commons, never advice (G1); no-server-key"
}
pathlib.Path("did-service.json").write_text(json.dumps(svc, indent=2) + "\n", encoding="utf-8")
print("DID service descriptor → wasm/did-service.json (ipfs://%s)" % cid)
PY

echo "OK — advertise wasm/did-service.json in the actor did.json (ipfs://$CID)."
