(ns mitooshi.methods.ingest
  "mitooshi 見通し — public time-series normalizer (R0, offline).
  Clojure port of methods/ingest.py (1:1, the pure core). ADR-2606051800.

  Normalizes a PUBLIC time-series batch (a watari/watatsuna chokepoint roll-up, an
  OpenSky-derived congestion series, a gov-open-data flow series, or a karakuri
  member-principal export) into kotoba-EDN :series/* + :obs/* datoms.

  CONSTITUTIONAL (mitooshi G4 + G11):
    - G4 source membrane: a series is normalized ONLY if its source-class is in the
      primary-public set; a proprietary-terminal source (Bloomberg/CapIQ/Refinitiv/四季報)
      or scraped Google-Trends series is REFUSED (counted + reasoned), never silently
      relabelled.
    - G11 honesty: everything is :representative; observations are append-only, sorted by
      observed-at (latest = current, the stream = the trail, 非終末論).

  The G10 live-fetch gate lives in the Python `main` (--live + MITOOSHI_OPERATOR_GATE),
  omitted from this port per the convention; `normalize` itself is pure (no I/O). stdlib only."
  (:require [clojure.string :as str]
            #?(:clj [cheshire.core :as json])))

;; G4 — the primary-public source classes; anything else is refused (kanjo §2(c)/(e)).
(def ALLOWED-SOURCE-CLASS
  ["public-broadcast" "primary-disclosure" "open-commons" "gov-open-data" "member-principal"])

(defn- norm*
  "(v or \"\").lstrip(\":\") — strip leading colons (a keyword-string → its bare token)."
  [v]
  (str/replace (str (or v "")) #"^:+" ""))

(defn normalize
  "Accepts {\"series\" [{id kind unit source sourceClass obs:[{observedAt value class?}]}]}.
  Returns {\"series\" {id datom} \"obs\" [datom] \"refused\" [{id sourceClass reason}]}.
  A series whose sourceClass is not primary-public is REFUSED (G4) — not normalized."
  [batch]
  (reduce
   (fn [acc s]
     (let [sid (get s "id")
           sc  (norm* (get s "sourceClass"))]
       (if-not (some #(= % sc) ALLOWED-SOURCE-CLASS)
         (update acc "refused" conj
                 {"id" sid "sourceClass" sc
                  "reason" (str "G4: source-class " (pr-str sc) " not in primary-public set "
                                (pr-str ALLOWED-SOURCE-CLASS) "; proprietary terminals + scraped "
                                "Google-Trends are unrepresentable (kanjo §2(c)/(e))")})
         (let [series-datom {":series/id" sid
                             ":series/name" (get s "name" sid)
                             ":series/kind" (str ":" (norm* (get s "kind" "transit-load")))
                             ":series/unit" (get s "unit" "")
                             ":series/freq" (str ":" (norm* (get s "freq" "daily")))
                             ":series/source" (get s "source" "")
                             ":series/source-class" (str ":" sc)
                             ":series/sourcing" ":representative"}
               sorted-obs (sort-by #(get % "observedAt" 0) (get s "obs" []))
               obs-datoms (mapv (fn [o]
                                  (cond-> {":obs/id" (str "obs." sid "." (get o "observedAt"))
                                           ":obs/series" sid
                                           ":obs/observed-at" (get o "observedAt")
                                           ":obs/value" (get o "value" 0.0)}
                                    (contains? o "class") (assoc ":obs/class" (get o "class"))))
                                sorted-obs)]
           (-> acc
               (assoc-in ["series" sid] series-datom)
               (update "obs" into obs-datoms))))))
   {"series" {} "obs" [] "refused" []}
   (get batch "series" [])))

(defn emit-edn
  "Serialise a normalized result to DERIVED :representative kotoba EDN (mirror of _emit_edn)."
  [norm]
  (let [head [";; series-graph.merged.kotoba.edn — DERIVED from offline ingest (:representative)."
              ";; ADR-2606051800 · generated by methods/ingest" "" "["]
        series-lines (map (fn [d]
                            (str " {:series/id \"" (get d ":series/id") "\" :series/kind "
                                 (get d ":series/kind") " :series/unit \"" (get d ":series/unit")
                                 "\" :series/source-class " (get d ":series/source-class")
                                 " :series/sourcing :representative}"))
                          (vals (get norm "series")))
        obs-lines (map (fn [d]
                         (str " {:obs/id \"" (get d ":obs/id") "\" :obs/series \""
                              (get d ":obs/series") "\" :obs/observed-at " (get d ":obs/observed-at")
                              " :obs/value " (get d ":obs/value")
                              (if (contains? d ":obs/class")
                                (str " :obs/class \"" (get d ":obs/class") "\"") "")
                              "}"))
                       (get norm "obs"))]
    (str/join "\n" (concat head series-lines obs-lines ["]"]))))

#?(:clj
   (defn load-batch
     "Read + parse a JSON batch file (string keys, like the Python dict)."
     [path]
     (json/parse-string (slurp (str path)))))
