#!/usr/bin/env bb
;; junkan 循環 — live SCORECARD generator (coverage + integrity + read-off digest).
(ns junkan.methods.scorecard
  "scorecard.cljc — junkan 循環 governance-asymmetry SCORECARD generator
  (ADR-2605290927). Renders a single markdown digest from the LIVE substrate:
  coverage counts, continental balance, kind/polarity mix, stock regimes, the
  era trajectory tail, and the validate.cljc integrity verdict — so the scorecard
  never drifts from the data (generated, not hand-maintained). Read-only (G4):
  `render` is pure; the `-main` writes the file. Mirrors the generated-MATURITY
  pattern of the hinagata/tatara family."
  (:require [junkan.methods.analyze :as az]
            [junkan.methods.validate :as v]
            [clojure.string :as str]))

(defn render
  "Pure: render the scorecard markdown from an analysis bundle + a validate result."
  [analysis validation]
  (let [cov (get analysis "coverage")
        stocks (get analysis "stocks")
        regions (:regions cov)
        traj (get analysis "trajectory")]
    (str
     "# junkan 循環 — governance-asymmetry SCORECARD (generated)\n\n"
     "_Generated by `methods/scorecard.cljc` from the live substrate — do not hand-edit._\n"
     "国民↔政府の非対称を system-dynamics で観る分析専用 observer (ADR-2605290927)。\n\n"
     "## Coverage\n\n"
     "- **instruments**: " (:instruments cov) "\n"
     "- **jurisdictions**: " (:jurisdictions cov) "\n"
     "- **kinds**: " (pr-str (:kinds cov)) "\n"
     "- **polarity**: " (pr-str (:polarity cov)) "\n"
     "- **sourcing**: " (pr-str (:sourcing cov)) "\n\n"
     "### Continental balance\n\n"
     (str/join "\n" (for [[r n] (sort-by (comp - val) regions)]
                      (str "- " (name r) ": " n)))
     "\n\n## Asymmetry stock regimes (HYPOTHESIS, G5)\n\n"
     "| stock | n | net | regime |\n|---|---|---|---|\n"
     (str/join "\n" (for [s az/stock-order
                          :let [sp (get stocks (name s))] :when sp]
                      (str "| " (name s) " | " (:count sp) " | " (:net sp)
                           " | " (name (:regime sp)) " |")))
     "\n\n## Era trajectory (net pressure of instruments enacted per era)\n\n"
     (str/join "\n" (for [e traj]
                      (str "- " (:era e) ": net " (:net e) " (n=" (:count e) ")")))
     "\n\n## Substrate integrity (validate.cljc)\n\n"
     "- **errors**: " (count (:errors validation)) "\n"
     "- **warnings**: " (count (:warnings validation)) "\n"
     "- **status**: " (if (empty? (:errors validation)) "✅ OK" "❌ has errors") "\n"
     "- **next focus (self-balancing)**: deepen the thinnest stock — **"
     (:thinnest-stock cov) "**\n\n"
     "_Discipline: G4 analysis-only · G5 hypothesis-only · G6 aggregate-only · "
     "G7 map-not-target-list · G11 candidates-not-directives._\n")))

#?(:clj
   (defn -main [& args]
     (let [seed (or (first args) "20-actors/junkan/kotoba/seed.governance-asymmetry.edn")
           onto (or (second args) "20-actors/junkan/kotoba/ontology.junkan-gov.edn")
           out (or (nth args 2 nil) "80-data/junkan-governance/SCORECARD.md")
           is (vec (filter #(= (:type %) :instrument) (clojure.edn/read-string (slurp seed))))
           enums (:enums (clojure.edn/read-string (slurp onto)))
           a (az/analyze is)
           val (v/check is enums)
           md (render a val)]
       (spit out md)
       (println (str "wrote " out " — " (count is) " instruments, integrity "
                     (if (empty? (:errors val)) "OK" "FAILED"))))))

#?(:clj
   (when (= *file* (System/getProperty "babashka.file"))
     (apply -main *command-line-args*)))
