"""
Py Kotodama WASM entrypoint for the Post_quantum clean-room actor (L4).

L4 production surface: CRUD + pagination + filtering + relationship
expansion + validation, over a Datomic-backed Kotoba schema.
Generated by 70-tools/promote_l4.py (ADR 260607 deepening phase, L4 cohort).
No proprietary code or credentials; resource shapes only.
"""
from kotodama import Runtime
from kotoba import load_schema
from datomic import DatomicClient
import uuid
import datetime

schema = load_schema("../schema/post_quantum.kotoba")
db = DatomicClient.connect()
app = Runtime("post_quantum-compat")

DEFAULT_LIMIT = 20
MAX_LIMIT = 100


def now():
    return datetime.datetime.utcnow().isoformat()


def new_id(prefix):
    return f"{prefix}_" + uuid.uuid4().hex[:16]


def _as_int(v):
    try:
        return int(v)
    except (TypeError, ValueError):
        return 0


def _as_float(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return 0.0


def _as_bool(v):
    return str(v).lower() in ("1", "true", "yes", "on") if v is not None else False


def _persist(entity, rec):
    """Transact a record into Datomic as namespaced EAVT facts."""
    facts = {}
    for k, v in rec.items():
        facts[f"post_quantum.{entity}/{k}"] = v
    db.transact([facts])
    return rec


def _query(entity, eid=None):
    pattern = {"entity": f"post_quantum.{entity}"}
    if eid is not None:
        pattern["id"] = eid
    return db.query(pattern)


def _require(data, fields):
    missing = [f for f in fields if not data.get(f)]
    if missing:
        return {"error": {"message": "Missing required fields: " + ", ".join(missing),
                          "type": "invalid_request_error"}}
    return None


def _reject_unknown(data, allowed):
    """Reject body fields not in the entity schema (strict validation)."""
    extra = [k for k in data if k not in allowed]
    if extra:
        return {"error": {"message": "Unknown fields: " + ", ".join(extra),
                          "type": "invalid_request_error"}}
    return None


def _apply_filters(rows, params, fields):
    """Filter rows by any schema field present in the query params."""
    out = rows
    for f in fields:
        if f in params and params[f] not in (None, ""):
            want = str(params[f])
            out = [r for r in out if str(r.get(f)) == want]
    return out


def _paginate(rows, params):
    """Cursor pagination: limit + starting_after (an id). Returns (page, has_more)."""
    limit = min(max(_as_int(params.get("limit")) or DEFAULT_LIMIT, 1), MAX_LIMIT)
    start = params.get("starting_after")
    if start is not None:
        ids = [r.get("id") for r in rows]
        if start in ids:
            rows = rows[ids.index(start) + 1:]
    page = rows[:limit]
    return page, len(rows) > limit


def _expand(rec, params, refs):
    """?expand=<field> inlines a referenced entity (rec[field+"_obj"])."""
    want = (params.get("expand") or "").split(",")
    for field, ent in refs.items():
        if field in want and rec.get(field):
            rows = _query(ent, rec[field])
            rec[field + "_obj"] = rows[0] if rows else None
    return rec


@app.route("/v1/keysessions", methods=["POST"])
def create_key_session(request):
    """Create a KeySession."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['aliceNodeId', 'bobNodeId', 'protocol', 'status'])
    if err:
        return err, 400
    err = _require(data, ['protocol', 'status'])
    if err:
        return err, 400
    rec = {"id": new_id("postquan_key")}
    rec["aliceNodeId"] = data.get('aliceNodeId')
    rec["bobNodeId"] = data.get('bobNodeId')
    rec["protocol"] = data.get('protocol')
    rec["status"] = data.get('status')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("KeySession", rec)
    return rec, 201

@app.route("/v1/keysessions", methods=["GET"])
def list_key_sessions(request):
    """List KeySessions with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("KeySession")
    rows = _apply_filters(rows, params, ['aliceNodeId', 'bobNodeId', 'protocol', 'status'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/keysessions/<eid>", methods=["GET"])
def get_key_session(request, eid):
    """Retrieve a KeySession by id (supports ?expand=)."""
    rows = _query("KeySession", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/keysessions/<eid>", methods=["POST", "PATCH"])
def update_key_session(request, eid):
    """Update a KeySession."""
    rows = _query("KeySession", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['aliceNodeId', 'bobNodeId', 'protocol', 'status'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("KeySession", rec)
    return rec, 200

@app.route("/v1/keysessions/<eid>", methods=["DELETE"])
def delete_key_session(request, eid):
    """Delete a KeySession."""
    rows = _query("KeySession", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"post_quantum.KeySession", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/nodes", methods=["POST"])
def create_node(request):
    """Create a Node."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'location', 'role'])
    if err:
        return err, 400
    err = _require(data, ['name', 'location'])
    if err:
        return err, 400
    rec = {"id": new_id("postquan_nod")}
    rec["name"] = data.get('name')
    rec["location"] = data.get('location')
    rec["role"] = data.get('role')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Node", rec)
    return rec, 201

@app.route("/v1/nodes", methods=["GET"])
def list_nodes(request):
    """List Nodes with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Node")
    rows = _apply_filters(rows, params, ['name', 'location', 'role'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/nodes/<eid>", methods=["GET"])
def get_node(request, eid):
    """Retrieve a Node by id (supports ?expand=)."""
    rows = _query("Node", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/nodes/<eid>", methods=["POST", "PATCH"])
def update_node(request, eid):
    """Update a Node."""
    rows = _query("Node", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'location', 'role'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Node", rec)
    return rec, 200

@app.route("/v1/nodes/<eid>", methods=["DELETE"])
def delete_node(request, eid):
    """Delete a Node."""
    rows = _query("Node", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"post_quantum.Node", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/channels", methods=["POST"])
def create_channel(request):
    """Create a Channel."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['sessionId', 'medium', 'lossDb'])
    if err:
        return err, 400
    err = _require(data, ['medium', 'lossDb'])
    if err:
        return err, 400
    rec = {"id": new_id("postquan_cha")}
    rec["sessionId"] = data.get('sessionId')
    rec["medium"] = data.get('medium')
    rec["lossDb"] = _as_float(data.get('lossDb'))
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Channel", rec)
    return rec, 201

@app.route("/v1/channels", methods=["GET"])
def list_channels(request):
    """List Channels with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Channel")
    rows = _apply_filters(rows, params, ['sessionId', 'medium', 'lossDb'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/channels/<eid>", methods=["GET"])
def get_channel(request, eid):
    """Retrieve a Channel by id (supports ?expand=)."""
    rows = _query("Channel", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/channels/<eid>", methods=["POST", "PATCH"])
def update_channel(request, eid):
    """Update a Channel."""
    rows = _query("Channel", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['sessionId', 'medium', 'lossDb'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Channel", rec)
    return rec, 200

@app.route("/v1/channels/<eid>", methods=["DELETE"])
def delete_channel(request, eid):
    """Delete a Channel."""
    rows = _query("Channel", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"post_quantum.Channel", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/keys", methods=["POST"])
def create_key(request):
    """Create a Key."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['sessionId', 'lengthBits', 'qber', 'contentRef'])
    if err:
        return err, 400
    err = _require(data, ['lengthBits', 'qber'])
    if err:
        return err, 400
    rec = {"id": new_id("postquan_key")}
    rec["sessionId"] = data.get('sessionId')
    rec["lengthBits"] = _as_int(data.get('lengthBits'))
    rec["qber"] = _as_float(data.get('qber'))
    rec["contentRef"] = data.get('contentRef')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Key", rec)
    return rec, 201

@app.route("/v1/keys", methods=["GET"])
def list_keys(request):
    """List Keys with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Key")
    rows = _apply_filters(rows, params, ['sessionId', 'lengthBits', 'qber', 'contentRef'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/keys/<eid>", methods=["GET"])
def get_key(request, eid):
    """Retrieve a Key by id (supports ?expand=)."""
    rows = _query("Key", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/keys/<eid>", methods=["POST", "PATCH"])
def update_key(request, eid):
    """Update a Key."""
    rows = _query("Key", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['sessionId', 'lengthBits', 'qber', 'contentRef'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Key", rec)
    return rec, 200

@app.route("/v1/keys/<eid>", methods=["DELETE"])
def delete_key(request, eid):
    """Delete a Key."""
    rows = _query("Key", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"post_quantum.Key", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/protocols", methods=["POST"])
def create_protocol(request):
    """Create a Protocol."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'family'])
    if err:
        return err, 400
    err = _require(data, ['name', 'family'])
    if err:
        return err, 400
    rec = {"id": new_id("postquan_pro")}
    rec["name"] = data.get('name')
    rec["family"] = data.get('family')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Protocol", rec)
    return rec, 201

@app.route("/v1/protocols", methods=["GET"])
def list_protocols(request):
    """List Protocols with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Protocol")
    rows = _apply_filters(rows, params, ['name', 'family'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/protocols/<eid>", methods=["GET"])
def get_protocol(request, eid):
    """Retrieve a Protocol by id (supports ?expand=)."""
    rows = _query("Protocol", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    return rec, 200

@app.route("/v1/protocols/<eid>", methods=["POST", "PATCH"])
def update_protocol(request, eid):
    """Update a Protocol."""
    rows = _query("Protocol", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['name', 'family'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Protocol", rec)
    return rec, 200

@app.route("/v1/protocols/<eid>", methods=["DELETE"])
def delete_protocol(request, eid):
    """Delete a Protocol."""
    rows = _query("Protocol", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"post_quantum.Protocol", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/v1/alarms", methods=["POST"])
def create_alarm(request):
    """Create a Alarm."""
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['nodeId', 'type', 'raisedAt'])
    if err:
        return err, 400
    err = _require(data, ['type', 'raisedAt'])
    if err:
        return err, 400
    rec = {"id": new_id("postquan_ala")}
    rec["nodeId"] = data.get('nodeId')
    rec["type"] = data.get('type')
    rec["raisedAt"] = data.get('raisedAt')
    rec["createdAt"] = now()
    rec["updatedAt"] = rec["createdAt"]
    _persist("Alarm", rec)
    return rec, 201

@app.route("/v1/alarms", methods=["GET"])
def list_alarms(request):
    """List Alarms with filtering + cursor pagination."""
    params = request.query or {}
    rows = _query("Alarm")
    rows = _apply_filters(rows, params, ['nodeId', 'type', 'raisedAt'])
    page, has_more = _paginate(rows, params)
    return {"object": "list", "data": page, "has_more": has_more,
            "count": len(page), "total": len(rows)}, 200

@app.route("/v1/alarms/<eid>", methods=["GET"])
def get_alarm(request, eid):
    """Retrieve a Alarm by id (supports ?expand=)."""
    rows = _query("Alarm", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    rec = rows[0]
    rec = _expand(rec, request.query or {}, {'nodeId': 'Node'})
    return rec, 200

@app.route("/v1/alarms/<eid>", methods=["POST", "PATCH"])
def update_alarm(request, eid):
    """Update a Alarm."""
    rows = _query("Alarm", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    data = request.json or request.form or {}
    err = _reject_unknown(data, ['nodeId', 'type', 'raisedAt'])
    if err:
        return err, 400
    rec = rows[0]
    for k, v in data.items():
        if k not in ("id", "createdAt"):
            rec[k] = v
    rec["updatedAt"] = now()
    _persist("Alarm", rec)
    return rec, 200

@app.route("/v1/alarms/<eid>", methods=["DELETE"])
def delete_alarm(request, eid):
    """Delete a Alarm."""
    rows = _query("Alarm", eid)
    if not rows:
        return {"error": {"message": "Not found", "type": "not_found"}}, 404
    db.retract({"entity": f"post_quantum.Alarm", "id": eid})
    return {"id": eid, "deleted": True}, 200

@app.route("/healthz", methods=["GET"])
def healthz(request):
    return {"status": "ok", "actor": "post_quantum-compat", "tier": "L4",
            "entities": ['KeySession', 'Node', 'Channel', 'Key', 'Protocol', 'Alarm']}, 200


if __name__ == "__main__":
    app.start()
