#!/usr/bin/env python3
"""gen_coverage_doc.py — render COVERAGE.md from the live registry (maturity).

Persists the atlas_summary + coverage_matrix dashboards as a committed, browsable
Markdown document so the atlas's shape & per-country completeness are reviewable on
GitHub without running anything. Re-run after data changes:  python3 gen_coverage_doc.py
"""
from __future__ import annotations

import glob
import os
import re
import sys
from collections import Counter, defaultdict

_HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.normpath(os.path.join(_HERE, "..", "cells", "reconcile")))
sys.path.insert(0, _HERE)
from cell import parse_edn  # noqa: E402
from coverage_matrix import CAT, SUF2CAT  # noqa: E402

_REG = os.path.normpath(os.path.join(_HERE, "..", "registry"))
_OUT = os.path.normpath(os.path.join(_HERE, "..", "COVERAGE.md"))


def main() -> int:
    units = {}
    addr = 0
    coords = 0
    procedures = []
    for f in sorted(glob.glob(os.path.join(_REG, "gov-units*.edn"))):
        doc = parse_edn(open(f, encoding="utf-8").read())
        for u in doc.get(":units", []):
            if u.get(":gov.unit/id"):
                units[u[":gov.unit/id"]] = u
        for a in doc.get(":addresses", []):
            addr += 1
            if a.get(":gov.address/lat") is not None:
                coords += 1
        procedures.extend(doc.get(":procedures", []))
    by_level = Counter(u.get(":gov.unit/level", "—") for u in units.values())
    by_branch = Counter(u.get(":gov.unit/branch", "—") for u in units.values())
    by_src = Counter(u.get(":gov.unit/sourcing", "—") for u in units.values())
    countries = sorted(j for j in {u.get(":gov.unit/jurisdiction") for u in units.values()
                                   if u.get(":gov.unit/level") == ":country"} if j and len(j) == 3)
    have = defaultdict(set)
    nat = re.compile(r"^gov\.([a-z]{3})\.([a-z0-9-]+)$")
    for uid in units:
        m = nat.match(uid)
        if m and SUF2CAT.get(m.group(2)):
            have[m.group(1)].add(SUF2CAT[m.group(2)])
    L = []
    L.append("# ooyake 公 — atlas coverage report")
    L.append("")
    L.append("_Auto-generated by `scripts/gen_coverage_doc.py` from the committed registry. "
             "Do not hand-edit — re-run after data changes._")
    L.append("")
    L.append(f"**{len(units):,} government units** across **{len(countries)} sovereign jurisdictions** · "
             f"**{addr:,} addresses** ({coords:,} with lat/lon) · "
             f"sourcing: " + ", ".join(f"{k.lstrip(':')} {v:,}" for k, v in by_src.most_common()))
    L.append("")
    L.append("## By level")
    L.append("")
    L.append("| level | units |")
    L.append("|---|--:|")
    for k, v in by_level.most_common():
        L.append(f"| {k.lstrip(':')} | {v:,} |")
    L.append("")
    L.append("## By branch")
    L.append("")
    L.append("| branch | units |")
    L.append("|---|--:|")
    for k, v in by_branch.most_common():
        L.append(f"| {str(k).lstrip(':')} | {v:,} |")
    L.append("")
    L.append("## Functional coverage (national bodies)")
    L.append("")
    L.append(f"How many of the {len(countries)} sovereign jurisdictions carry each functional body type.")
    L.append("")
    L.append("| category | countries | % |")
    L.append("|---|--:|--:|")
    cat_cov = {c: sum(1 for iso in countries if c in have[iso]) for c in CAT}
    for c, n in sorted(cat_cov.items(), key=lambda x: -x[1]):
        L.append(f"| {c} | {n} | {round(100*n/max(1,len(countries)))}% |")
    L.append("")
    comp = sorted(((len(have[iso]), iso) for iso in countries), reverse=True)
    avg = sum(n for n, _ in comp) / max(1, len(comp))
    L.append(f"## Per-country completeness — avg **{avg:.1f}/{len(CAT)}** categories")
    L.append("")
    L.append("Most complete: " + ", ".join(f"{iso.upper()} ({n})" for n, iso in comp[:12]))
    L.append("")
    L.append("Thinnest: " + ", ".join(f"{iso.upper()} ({n})" for n, iso in comp[-12:]))
    L.append("")
    L.append("> Observational mirror (G3/G11): a descriptive civic structural map, never a "
             "target-list, never ranked as judgement — completeness here reflects Wikidata "
             "typing coverage, not a country's governance quality.")
    L.append("")

    # ── Procedure linkage (illustrative; NOT counted as authoritative coverage, G5) ──
    if procedures:
        proc_juris = {p.get(":gov.procedure/jurisdiction") for p in procedures}
        proc_juris.discard(None)
        by_proc_src = Counter(p.get(":gov.procedure/sourcing", "—") for p in procedures)
        linked = [p for p in procedures if p.get(":gov.procedure/toritsugi-ref")]
        # cross-actor link resolution (read-only; degrade gracefully if file absent)
        resolved = "—"
        tor_path = os.path.normpath(
            os.path.join(_HERE, "..", "..", "toritsugi", "registry", "procedures.seed.json")
        )
        try:
            import json
            tids = {p["procedureId"] for p in json.load(open(tor_path, encoding="utf-8"))["procedures"]}
            resolved = sum(1 for p in linked if p.get(":gov.procedure/toritsugi-ref") in tids)
        except Exception:
            pass
        L.append("## Procedure linkage (illustrative)")
        L.append("")
        L.append(f"**{len(procedures)} `:gov.procedure` records** across "
                 f"**{len(proc_juris)} jurisdictions**, "
                 f"{len(linked)} linked to toritsugi via `:gov.procedure/toritsugi-ref` "
                 f"({resolved} resolve to a live toritsugi procedureId).")
        L.append("")
        L.append("| sourcing | procedures |")
        L.append("|---|--:|")
        for k, v in by_proc_src.most_common():
            L.append(f"| {str(k).lstrip(':')} | {v:,} |")
        L.append("")
        L.append("> **Honesty (G5)**: these procedure rows are `:representative` / "
                 "`:unverified-seed` wayfinding scaffold — they are **NOT authoritative "
                 "coverage** and are never counted as such. They project the citizen-facing "
                 "toritsugi procedures into the atlas tree (delivery ↔ structure) for "
                 "navigation only; live use requires verification (toritsugi G14).")
        L.append("")

    with open(_OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
    print(f"wrote {_OUT} — {len(units)} units, {len(countries)} jurisdictions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
