#!/usr/bin/env python3
"""gen_intl_procedures.py — project the worldwide toritsugi (取次) procedures into
the ooyake (公) gov-atlas as `:gov.procedure` records (maturity / reproducibility).

Generalises the original passport-only projection to the FULL toritsugi registry
(passport / national-id / tax / social-security / civil-registration). Emits
`registry/gov-units.intl-procedures.seed.edn` — one atlas procedure per non-JP
toritsugi `procedureId`, linked back via `:gov.procedure/toritsugi-ref`. Re-run
after editing the toritsugi registry:

    python3 20-actors/ooyake/scripts/gen_intl_procedures.py

HONEST owner-unit (G5): owner-unit = the COUNTRY-level `gov.<iso>` unit
(unambiguous, always resolvable), NOT a specific ministry — the issuing authority
differs by country and procedure, and asserting one ministry-unit uniformly would
fabricate the owner. The precise body is carried verbatim in
`:gov.procedure/owner-authority` (from the toritsugi `authority` field).
`eu-wide` procedures map to the EU supranational unit `gov.eu`.

Skipped (honest, logged): `jpn` (6 richer hand-authored procedures already live in
gov-units.toritsugi-procedures.seed.edn) and any jurisdiction with no resolvable
atlas owner-unit. All output rows are `:representative` / `:unverified-seed`
(never counted as authoritative coverage, G5).

NO fabrication: toritsugi's real requiredDocuments / legalBasis / channelType /
provenance are carried over verbatim; only fee + statutory-days are left to
guide-time resolution rather than invented.
"""
from __future__ import annotations

import glob
import json
import os
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_REPO = _HERE.parents[2]
_REG = _REPO / "20-actors" / "ooyake" / "registry"
_TORITSUGI = _REPO / "20-actors" / "toritsugi" / "registry" / "procedures.seed.json"
_OUT = _REG / "gov-units.intl-procedures.seed.edn"

sys.path.insert(0, str(_REPO / "20-actors" / "ooyake" / "cells" / "reconcile"))
from cell import parse_edn  # noqa: E402

# toritsugi jurisdiction code -> atlas owner-unit override (where iso != gov.<iso>)
_OWNER_OVERRIDE = {"eu-wide": "gov.eu"}


def _edn_str(s) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def _edn_vec(items) -> str:
    if not items:
        return "[]"
    return "[" + " ".join(_edn_str(x) for x in items) + "]"


def _channel_kw(ct: str) -> str:
    ct = (ct or "").lower()
    ks = []
    if "online" in ct:
        ks.append(":online")
    if "person" in ct:
        ks.append(":in-person")
    if "mail" in ct:
        ks.append(":mail")
    if not ks:
        ks = [":online", ":in-person"]
    return "[" + " ".join(ks) + "]"


def _atlas_units() -> set[str]:
    units: set[str] = set()
    for f in sorted(glob.glob(str(_REG / "gov-units*.edn"))):
        if os.path.basename(f) == _OUT.name:
            continue  # don't read our own output
        for u in parse_edn(open(f, encoding="utf-8").read()).get(":units", []):
            if u.get(":gov.unit/id"):
                units.add(u[":gov.unit/id"])
    return units


def _owner_for(iso: str, units: set[str]) -> str | None:
    cand = _OWNER_OVERRIDE.get(iso, f"gov.{iso}")
    return cand if cand in units else None


def main() -> int:
    units = _atlas_units()
    tor = json.loads(_TORITSUGI.read_text())["procedures"]

    rows, skipped = [], {}
    for p in tor:
        iso = p["jurisdiction"]
        if iso == "jpn":
            skipped["jpn (hand-authored)"] = skipped.get("jpn (hand-authored)", 0) + 1
            continue
        owner = _owner_for(iso, units)
        if not owner:
            skipped[f"no-unit:{iso}"] = skipped.get(f"no-unit:{iso}", 0) + 1
            continue
        rows.append((p, owner))

    out = [
        ";; ooyake 公 — gov-units.intl-procedures.seed.edn",
        ";;",
        ";; ALL non-JP toritsugi procedures projected into the gov-atlas as :gov.procedure.",
        ";; AUTO-GENERATED by scripts/gen_intl_procedures.py — do not hand-edit; re-run after",
        ";; toritsugi registry changes. owner-unit = country-level gov.<iso> (honest, G5);",
        ";; precise body in :gov.procedure/owner-authority. All :representative/:unverified-seed.",
        "{:procedures",
        " [",
    ]
    for p, owner in rows:
        iso, pid = p["jurisdiction"], p["procedureId"]
        title = p.get("title") or pid
        parts = [
            "  {:gov.procedure/id " + _edn_str(f"proc.{pid}"),
            "   :gov.procedure/title-local " + _edn_str(title)
            + " :gov.procedure/title-en " + _edn_str(title),
            "   :gov.procedure/owner-unit " + _edn_str(owner)
            + " :gov.procedure/owner-authority " + _edn_str(p.get("authority") or ""),
            "   :gov.procedure/jurisdiction " + _edn_str(iso)
            + " :gov.procedure/channel " + _channel_kw(p.get("channelType")),
            "   :gov.procedure/required-docs " + _edn_vec(p.get("requiredDocuments") or []),
        ]
        if p.get("legalBasis"):
            parts.append("   :gov.procedure/legal-basis " + _edn_str(p["legalBasis"]))
        parts.append('   :gov.procedure/fee "(see toritsugi / resolve at guide time)"')
        parts.append("   :gov.procedure/bpmn \"bpmn.ooyake.find-service\" "
                     ":gov.procedure/toritsugi-ref " + _edn_str(pid))
        parts.append("   :gov.procedure/sourcing :representative :gov.procedure/provenance "
                     + _edn_str(p.get("provenance") or "https://etzhayyim.com/"))
        parts.append('   :gov.procedure/last-verified "2026-06-05" '
                     ":gov.procedure/verification-status :unverified-seed}")
        out.append("\n".join(parts))
    out.append(" ]}")
    text = "\n".join(out) + "\n"
    _OUT.write_text(text, encoding="utf-8")

    n = len(parse_edn(text).get(":procedures", []))
    juris = len({p["jurisdiction"] for p, _ in rows})
    print(f"wrote {_OUT.name}: {n} procedures across {juris} jurisdictions")
    print(f"skipped: {skipped}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
