(ns x86_cpu.actor
  "x86_cpu clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). x86 CPU microarchitecture design.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; X86Core
   {:db/ident :x86_cpu.X86Core/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :x86_cpu.X86Core/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.X86Core/isa :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.X86Core/microarch :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.X86Core/frequencyGhz :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.X86Core/issueWidth :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.X86Core/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.X86Core/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ExecPort
   {:db/ident :x86_cpu.ExecPort/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :x86_cpu.ExecPort/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.ExecPort/index :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.ExecPort/units :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.ExecPort/throughput :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.ExecPort/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.ExecPort/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; MicroOp
   {:db/ident :x86_cpu.MicroOp/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :x86_cpu.MicroOp/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.MicroOp/mnemonic :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.MicroOp/fusedDomain :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.MicroOp/latency :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.MicroOp/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.MicroOp/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; CacheLevel
   {:db/ident :x86_cpu.CacheLevel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :x86_cpu.CacheLevel/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.CacheLevel/level :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.CacheLevel/sizeKb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.CacheLevel/associativity :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.CacheLevel/latencyCycles :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.CacheLevel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.CacheLevel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; TlbLevel
   {:db/ident :x86_cpu.TlbLevel/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :x86_cpu.TlbLevel/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.TlbLevel/level :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.TlbLevel/entries :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.TlbLevel/pageSizeKb :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.TlbLevel/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.TlbLevel/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; PowerState
   {:db/ident :x86_cpu.PowerState/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :x86_cpu.PowerState/coreId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.PowerState/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.PowerState/voltageV :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.PowerState/tdpW :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.PowerState/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :x86_cpu.PowerState/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"X86Core" "ExecPort" "MicroOp" "CacheLevel" "TlbLevel" "PowerState"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "x86_cpu: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "x86_cpu: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "x86_cpu: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── X86Core ────────────────────────────────────────────────────────────────
(defn create-x86-core
  "Create a X86Core."
  [port data]
  (require-fields data ["name" "isa"])
  (let [id (new-id "xcpu_x86")
        e {:db/id id
           :x86_cpu.X86Core/id id
           :x86_cpu.X86Core/name (get data :name)
           :x86_cpu.X86Core/isa (get data :isa)
           :x86_cpu.X86Core/microarch (get data :microarch)
           :x86_cpu.X86Core/frequencyGhz (as-double (get data :frequencyGhz))
           :x86_cpu.X86Core/issueWidth (as-long (get data :issueWidth))
           :x86_cpu.X86Core/createdAt (now)
           :x86_cpu.X86Core/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-x86-cores
  "List X86Core with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-x86-cores port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :x86_cpu.X86Core/id))
         rows (apply-filters rows (:filter opts) [:x86_cpu.X86Core/name :x86_cpu.X86Core/isa :x86_cpu.X86Core/microarch :x86_cpu.X86Core/frequencyGhz :x86_cpu.X86Core/issueWidth])]
     (paginate rows opts))))

(defn get-x86-core
  "Retrieve a X86Core by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-x86-core port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-x86-core
  "Update a X86Core; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :x86_cpu.X86Core/name (get data :name)]))
                   (cond-> (contains? data :isa) (conj [:db/add id :x86_cpu.X86Core/isa (get data :isa)]))
                   (cond-> (contains? data :microarch) (conj [:db/add id :x86_cpu.X86Core/microarch (get data :microarch)]))
                   (cond-> (contains? data :frequencyGhz) (conj [:db/add id :x86_cpu.X86Core/frequencyGhz (as-double (get data :frequencyGhz))]))
                   (cond-> (contains? data :issueWidth) (conj [:db/add id :x86_cpu.X86Core/issueWidth (as-long (get data :issueWidth))]))
                   (conj [:db/add id :x86_cpu.X86Core/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-x86-core
  "Delete a X86Core."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ExecPort ────────────────────────────────────────────────────────────────
(defn create-exec-port
  "Create a ExecPort."
  [port data]
  (require-fields data ["index" "units"])
  (let [id (new-id "xcpu_exe")
        e {:db/id id
           :x86_cpu.ExecPort/id id
           :x86_cpu.ExecPort/coreId (get data :coreId)
           :x86_cpu.ExecPort/index (as-long (get data :index))
           :x86_cpu.ExecPort/units (get data :units)
           :x86_cpu.ExecPort/throughput (as-long (get data :throughput))
           :x86_cpu.ExecPort/createdAt (now)
           :x86_cpu.ExecPort/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-exec-ports
  "List ExecPort with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-exec-ports port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :x86_cpu.ExecPort/id))
         rows (apply-filters rows (:filter opts) [:x86_cpu.ExecPort/coreId :x86_cpu.ExecPort/index :x86_cpu.ExecPort/units :x86_cpu.ExecPort/throughput])]
     (paginate rows opts))))

(defn get-exec-port
  "Retrieve a ExecPort by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-exec-port port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-exec-port
  "Update a ExecPort; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :x86_cpu.ExecPort/coreId (get data :coreId)]))
                   (cond-> (contains? data :index) (conj [:db/add id :x86_cpu.ExecPort/index (as-long (get data :index))]))
                   (cond-> (contains? data :units) (conj [:db/add id :x86_cpu.ExecPort/units (get data :units)]))
                   (cond-> (contains? data :throughput) (conj [:db/add id :x86_cpu.ExecPort/throughput (as-long (get data :throughput))]))
                   (conj [:db/add id :x86_cpu.ExecPort/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-exec-port
  "Delete a ExecPort."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── MicroOp ────────────────────────────────────────────────────────────────
(defn create-micro-op
  "Create a MicroOp."
  [port data]
  (require-fields data ["mnemonic" "fusedDomain"])
  (let [id (new-id "xcpu_mic")
        e {:db/id id
           :x86_cpu.MicroOp/id id
           :x86_cpu.MicroOp/coreId (get data :coreId)
           :x86_cpu.MicroOp/mnemonic (get data :mnemonic)
           :x86_cpu.MicroOp/fusedDomain (get data :fusedDomain)
           :x86_cpu.MicroOp/latency (as-long (get data :latency))
           :x86_cpu.MicroOp/createdAt (now)
           :x86_cpu.MicroOp/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-micro-ops
  "List MicroOp with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-micro-ops port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :x86_cpu.MicroOp/id))
         rows (apply-filters rows (:filter opts) [:x86_cpu.MicroOp/coreId :x86_cpu.MicroOp/mnemonic :x86_cpu.MicroOp/fusedDomain :x86_cpu.MicroOp/latency])]
     (paginate rows opts))))

(defn get-micro-op
  "Retrieve a MicroOp by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-micro-op port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-micro-op
  "Update a MicroOp; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :x86_cpu.MicroOp/coreId (get data :coreId)]))
                   (cond-> (contains? data :mnemonic) (conj [:db/add id :x86_cpu.MicroOp/mnemonic (get data :mnemonic)]))
                   (cond-> (contains? data :fusedDomain) (conj [:db/add id :x86_cpu.MicroOp/fusedDomain (get data :fusedDomain)]))
                   (cond-> (contains? data :latency) (conj [:db/add id :x86_cpu.MicroOp/latency (as-long (get data :latency))]))
                   (conj [:db/add id :x86_cpu.MicroOp/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-micro-op
  "Delete a MicroOp."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── CacheLevel ────────────────────────────────────────────────────────────────
(defn create-cache-level
  "Create a CacheLevel."
  [port data]
  (require-fields data ["level" "sizeKb"])
  (let [id (new-id "xcpu_cac")
        e {:db/id id
           :x86_cpu.CacheLevel/id id
           :x86_cpu.CacheLevel/coreId (get data :coreId)
           :x86_cpu.CacheLevel/level (get data :level)
           :x86_cpu.CacheLevel/sizeKb (as-long (get data :sizeKb))
           :x86_cpu.CacheLevel/associativity (as-long (get data :associativity))
           :x86_cpu.CacheLevel/latencyCycles (as-long (get data :latencyCycles))
           :x86_cpu.CacheLevel/createdAt (now)
           :x86_cpu.CacheLevel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-cache-levels
  "List CacheLevel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-cache-levels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :x86_cpu.CacheLevel/id))
         rows (apply-filters rows (:filter opts) [:x86_cpu.CacheLevel/coreId :x86_cpu.CacheLevel/level :x86_cpu.CacheLevel/sizeKb :x86_cpu.CacheLevel/associativity :x86_cpu.CacheLevel/latencyCycles])]
     (paginate rows opts))))

(defn get-cache-level
  "Retrieve a CacheLevel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-cache-level port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-cache-level
  "Update a CacheLevel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :x86_cpu.CacheLevel/coreId (get data :coreId)]))
                   (cond-> (contains? data :level) (conj [:db/add id :x86_cpu.CacheLevel/level (get data :level)]))
                   (cond-> (contains? data :sizeKb) (conj [:db/add id :x86_cpu.CacheLevel/sizeKb (as-long (get data :sizeKb))]))
                   (cond-> (contains? data :associativity) (conj [:db/add id :x86_cpu.CacheLevel/associativity (as-long (get data :associativity))]))
                   (cond-> (contains? data :latencyCycles) (conj [:db/add id :x86_cpu.CacheLevel/latencyCycles (as-long (get data :latencyCycles))]))
                   (conj [:db/add id :x86_cpu.CacheLevel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-cache-level
  "Delete a CacheLevel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── TlbLevel ────────────────────────────────────────────────────────────────
(defn create-tlb-level
  "Create a TlbLevel."
  [port data]
  (require-fields data ["level" "entries"])
  (let [id (new-id "xcpu_tlb")
        e {:db/id id
           :x86_cpu.TlbLevel/id id
           :x86_cpu.TlbLevel/coreId (get data :coreId)
           :x86_cpu.TlbLevel/level (get data :level)
           :x86_cpu.TlbLevel/entries (as-long (get data :entries))
           :x86_cpu.TlbLevel/pageSizeKb (as-long (get data :pageSizeKb))
           :x86_cpu.TlbLevel/createdAt (now)
           :x86_cpu.TlbLevel/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-tlb-levels
  "List TlbLevel with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-tlb-levels port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :x86_cpu.TlbLevel/id))
         rows (apply-filters rows (:filter opts) [:x86_cpu.TlbLevel/coreId :x86_cpu.TlbLevel/level :x86_cpu.TlbLevel/entries :x86_cpu.TlbLevel/pageSizeKb])]
     (paginate rows opts))))

(defn get-tlb-level
  "Retrieve a TlbLevel by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-tlb-level port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-tlb-level
  "Update a TlbLevel; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :x86_cpu.TlbLevel/coreId (get data :coreId)]))
                   (cond-> (contains? data :level) (conj [:db/add id :x86_cpu.TlbLevel/level (get data :level)]))
                   (cond-> (contains? data :entries) (conj [:db/add id :x86_cpu.TlbLevel/entries (as-long (get data :entries))]))
                   (cond-> (contains? data :pageSizeKb) (conj [:db/add id :x86_cpu.TlbLevel/pageSizeKb (as-long (get data :pageSizeKb))]))
                   (conj [:db/add id :x86_cpu.TlbLevel/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-tlb-level
  "Delete a TlbLevel."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── PowerState ────────────────────────────────────────────────────────────────
(defn create-power-state
  "Create a PowerState."
  [port data]
  (require-fields data ["name" "voltageV"])
  (let [id (new-id "xcpu_pow")
        e {:db/id id
           :x86_cpu.PowerState/id id
           :x86_cpu.PowerState/coreId (get data :coreId)
           :x86_cpu.PowerState/name (get data :name)
           :x86_cpu.PowerState/voltageV (as-double (get data :voltageV))
           :x86_cpu.PowerState/tdpW (as-double (get data :tdpW))
           :x86_cpu.PowerState/createdAt (now)
           :x86_cpu.PowerState/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-power-states
  "List PowerState with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-power-states port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :x86_cpu.PowerState/id))
         rows (apply-filters rows (:filter opts) [:x86_cpu.PowerState/coreId :x86_cpu.PowerState/name :x86_cpu.PowerState/voltageV :x86_cpu.PowerState/tdpW])]
     (paginate rows opts))))

(defn get-power-state
  "Retrieve a PowerState by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-power-state port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-power-state
  "Update a PowerState; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :coreId) (conj [:db/add id :x86_cpu.PowerState/coreId (get data :coreId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :x86_cpu.PowerState/name (get data :name)]))
                   (cond-> (contains? data :voltageV) (conj [:db/add id :x86_cpu.PowerState/voltageV (as-double (get data :voltageV))]))
                   (cond-> (contains? data :tdpW) (conj [:db/add id :x86_cpu.PowerState/tdpW (as-double (get data :tdpW))]))
                   (conj [:db/add id :x86_cpu.PowerState/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-power-state
  "Delete a PowerState."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/x86cores" :op :create :entity "X86Core"}
   {:method "GET" :path "/v1/x86cores" :op :list :entity "X86Core"}
   {:method "GET" :path "/v1/x86cores/:id" :op :get :entity "X86Core"}
   {:method "PATCH" :path "/v1/x86cores/:id" :op :update :entity "X86Core"}
   {:method "DELETE" :path "/v1/x86cores/:id" :op :delete :entity "X86Core"}
   {:method "POST" :path "/v1/execports" :op :create :entity "ExecPort"}
   {:method "GET" :path "/v1/execports" :op :list :entity "ExecPort"}
   {:method "GET" :path "/v1/execports/:id" :op :get :entity "ExecPort"}
   {:method "PATCH" :path "/v1/execports/:id" :op :update :entity "ExecPort"}
   {:method "DELETE" :path "/v1/execports/:id" :op :delete :entity "ExecPort"}
   {:method "POST" :path "/v1/microops" :op :create :entity "MicroOp"}
   {:method "GET" :path "/v1/microops" :op :list :entity "MicroOp"}
   {:method "GET" :path "/v1/microops/:id" :op :get :entity "MicroOp"}
   {:method "PATCH" :path "/v1/microops/:id" :op :update :entity "MicroOp"}
   {:method "DELETE" :path "/v1/microops/:id" :op :delete :entity "MicroOp"}
   {:method "POST" :path "/v1/cachelevels" :op :create :entity "CacheLevel"}
   {:method "GET" :path "/v1/cachelevels" :op :list :entity "CacheLevel"}
   {:method "GET" :path "/v1/cachelevels/:id" :op :get :entity "CacheLevel"}
   {:method "PATCH" :path "/v1/cachelevels/:id" :op :update :entity "CacheLevel"}
   {:method "DELETE" :path "/v1/cachelevels/:id" :op :delete :entity "CacheLevel"}
   {:method "POST" :path "/v1/tlblevels" :op :create :entity "TlbLevel"}
   {:method "GET" :path "/v1/tlblevels" :op :list :entity "TlbLevel"}
   {:method "GET" :path "/v1/tlblevels/:id" :op :get :entity "TlbLevel"}
   {:method "PATCH" :path "/v1/tlblevels/:id" :op :update :entity "TlbLevel"}
   {:method "DELETE" :path "/v1/tlblevels/:id" :op :delete :entity "TlbLevel"}
   {:method "POST" :path "/v1/powerstates" :op :create :entity "PowerState"}
   {:method "GET" :path "/v1/powerstates" :op :list :entity "PowerState"}
   {:method "GET" :path "/v1/powerstates/:id" :op :get :entity "PowerState"}
   {:method "PATCH" :path "/v1/powerstates/:id" :op :update :entity "PowerState"}
   {:method "DELETE" :path "/v1/powerstates/:id" :op :delete :entity "PowerState"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"x86cores" {:create create-x86-core :list list-x86-cores :get get-x86-core :update update-x86-core :delete delete-x86-core}
   "execports" {:create create-exec-port :list list-exec-ports :get get-exec-port :update update-exec-port :delete delete-exec-port}
   "microops" {:create create-micro-op :list list-micro-ops :get get-micro-op :update update-micro-op :delete delete-micro-op}
   "cachelevels" {:create create-cache-level :list list-cache-levels :get get-cache-level :update update-cache-level :delete delete-cache-level}
   "tlblevels" {:create create-tlb-level :list list-tlb-levels :get get-tlb-level :update update-tlb-level :delete delete-tlb-level}
   "powerstates" {:create create-power-state :list list-power-states :get get-power-state :update update-power-state :delete delete-power-state}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "x86_cpu-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
