#!/usr/bin/env bash
# kadode 門出 — build the kotoba pywasm component + content-address it (ADR-2606112238).
# Operator/mesh-side. Requires componentize-py (NOT a runtime dep):
#   pipx install componentize-py
#
# Produces dist/kadode.wasm (implementing wit/world.wit), its CIDv1, and the DID-doc service
# descriptor. The component embeds the bounded PUBLIC labour-law seed only — G1 (使者-not-agent)
# and no-server-key hold in WASM (the `relay` export builds an UNSENT record, refusing
# negotiation-needing scenarios).
set -euo pipefail
cd "$(dirname "$0")"
DIST="dist"; mkdir -p "$DIST"

python3 - <<'PY'
import pathlib, json
seed = pathlib.Path("../data/seed-resignation-graph.kotoba.edn").read_text(encoding="utf-8")
pathlib.Path("_embedded_seed.py").write_text(
    "# GENERATED by wasm/build.sh — bounded PUBLIC labour-law seed for the WASM component.\n"
    "# kadode is a 使者 (messenger) + concierge, never an agent or the practice of law (G1).\n"
    "SEED_EDN = " + json.dumps(seed) + "\n", encoding="utf-8")
print("embedded seed →", len(seed), "bytes")
PY

componentize-py -d wit -w kadode-actor componentize app \
  --module-path . --module-path ../methods \
  -o "$DIST/kadode.wasm"

CID=$(ipfs add -Q --cid-version=1 --raw-leaves "$DIST/kadode.wasm")
echo "$CID" > "$DIST/kadode.cid"
echo "component CID: $CID"

python3 - "$CID" <<'PY'
import sys, json, pathlib
cid = sys.argv[1]
svc = {
  "id": "did:web:etzhayyim.com:actor:kadode#wasm",
  "type": "EtzhayyimWasmComponent",
  "serviceEndpoint": f"ipfs://{cid}",
  "world": "etzhayyim:kadode/kadode-actor@0.1.0",
  "exports": ["analyze", "datoms", "coverage", "generate", "relay"],
  "tier": "T1-raw-browser-local",
  "scope": "PUBLIC Japanese labour law only — 使者/concierge, never agent or practice of law (G1); no-server-key"
}
pathlib.Path("did-service.json").write_text(json.dumps(svc, indent=2) + "\n", encoding="utf-8")
print("DID service descriptor → wasm/did-service.json (ipfs://%s)" % cid)
PY

echo "OK — advertise wasm/did-service.json in the actor did.json (ipfs://$CID)."
